Repository mermaid-js/mermaid, pull requests merged in 2019-12, with the labels that each got.

#1107 Feature/1106 Release management
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-draft.yml
  .github/workflows/release-preview-publish.yml
  .github/workflows/release-publish.yml
Labels: Area: DevOps, Type: Enhancement

#1114 Feature/1112 Revert to offical dagre d3
  package.json
  src/diagrams/flowchart/flowChartShapes.js
  src/diagrams/flowchart/flowRenderer.js
  webpack.config.base.js
  yarn.lock
Labels: Type: Enhancement

#1116 Bug/1110 state diagram rendering composit state
  .github/FUNDING.yml
  cypress/integration/rendering/current.spec.js
  cypress/integration/rendering/stateDiagram.spec.js
  cypress/platform/current.html
  src/diagrams/state/shapes.js
  src/diagrams/state/stateRenderer.js
  src/themes/state.scss
Labels: Type: Bug / Error

#1125 Bug/903 flowchart escaping in non html mode
  cypress/integration/other/xss.spec.js
  cypress/integration/rendering/gitGraph.spec.js
  cypress/platform/current.html
  cypress/platform/viewer.js
  cypress/platform/xss.html
  src/diagrams/flowchart/flowDb.js
Labels: Type: Bug / Error

#1126 #935 Fix for stylink of links. Default theme colors are picked up and…
  cypress/platform/current.html
  src/diagrams/flowchart/flowRenderer.js
Labels: Type: Bug / Error

#1129 Master sync
  .github/release-drafter.yml
Labels: Skip changelog

#1121 Add pull request template
  .github/pull_request_template.md
Labels: Skip changelog

#1120 Class: Generic type support
  cypress/integration/rendering/classDiagram.spec.js
  dist/index.html
  src/diagrams/class/classDb.js
  src/diagrams/class/classDiagram.spec.js
  src/diagrams/class/classRenderer.js
  src/diagrams/class/parser/classDiagram.jison
Labels: Graph: Class, Type: Enhancement

#1128 #1127 Ugrading of webpack and adding newer terser-webpack-plugin
  package.json
  yarn.lock
Labels: Skip changelog, Type: Bug / Error

#1130 Flow: Add stadium shape for nodes
  dist/index.html
  docs/flowchart.md
  src/diagrams/flowchart/flowChartShapes.js
  src/diagrams/flowchart/flowChartShapes.spec.js
  src/diagrams/flowchart/flowRenderer.js
  src/diagrams/flowchart/flowRenderer.spec.js
  src/diagrams/flowchart/parser/flow.jison
Labels: Type: Enhancement

#1137 Master sync
  .github/pull_request_template.md
Labels: Skip changelog

#1144 #1143 Fixing up the color output of the logger
  src/logger.js
Labels: Type: Other

#1148 #1142 Simplified arrows/edges in the grammar
  cypress/platform/current.html
  src/diagrams/flowchart/flowDb.js
  src/diagrams/flowchart/parser/flow-edges.spec.js
  src/diagrams/flowchart/parser/flow-text.spec.js
  src/diagrams/flowchart/parser/flow.jison
  src/mermaid.js
Labels: Type: Other

#1149 #1143 Adding support in grammar for multiple nodes in dependency decl…
  src/diagrams/flowchart/flowDb.js
  src/diagrams/flowchart/parser/flow-singlenode.spec.js
  src/diagrams/flowchart/parser/flow.jison
  src/diagrams/flowchart/parser/subgraph.spec.js
  src/diagrams/pie/parser/pie.jison
Labels: Type: Other

#1140 Removed docs reference to mermaidAPI.js
  docs/usage.md
Labels: Skip changelog, Type: Bug / Error

#1151 Git graph not clearing
  src/diagrams/git/gitGraphRenderer.js
Labels: Graph: Git, Type: Bug / Error

#1153 Bug/702 br tags in sequence diagrams
  cypress/integration/rendering/sequencediagram.spec.js
  dist/index.html
  src/diagrams/sequence/sequenceDiagram.spec.js
  src/diagrams/sequence/sequenceRenderer.js
  src/diagrams/sequence/svgDraw.js
Labels: Type: Bug / Error

#1159 Check tests on PR
  .github/workflows/checks.yml
Labels: Area: DevOps, Type: Enhancement

#1156 Extend the `br` tag regex
  cypress/integration/rendering/sequencediagram.spec.js
  dist/index.html
  src/diagrams/flowchart/flowRenderer.js
  src/diagrams/sequence/sequenceDiagram.spec.js
  src/diagrams/sequence/sequenceRenderer.js
  src/diagrams/sequence/svgDraw.js
Labels: Graph: Sequence, Type: Bug / Error

#1162 Fix infinite loop caused by date iteration
  cypress/integration/rendering/gantt.spec.js
  src/diagrams/gantt/ganttDb.js
  src/diagrams/gantt/ganttDb.spec.js
Labels: Graph: Gantt, Type: Bug / Error

#1163 Bug/Clicking on a link only works directly on the node text
  src/diagrams/flowchart/flowRenderer.js
Labels: Graph: Flow, Type: Bug / Error
