Repository mermaid-js/mermaid, pull requests merged in 2020-07, with the labels that each got.

#1523 Directives, sequenceDiagram refactor, config normalization, many tweaks
  cypress/integration/rendering/sequencediagram.spec.js
  dist/mermaid.core.js
  dist/mermaid.core.js.map
  dist/mermaid.js
  dist/mermaid.js.map
  dist/mermaid.min.js
  dist/mermaid.min.js.map
  docs/mermaidAPI.md
  src/config.js
  src/config.spec.js
  src/diagrams/common/common.js
  src/diagrams/sequence/parser/sequenceDiagram.jison
  src/diagrams/sequence/sequenceDb.js
  src/diagrams/sequence/sequenceDiagram.spec.js
  src/diagrams/sequence/sequenceRenderer.js
  src/diagrams/sequence/svgDraw.js
  src/mermaid.js
  src/mermaidAPI.js
  src/mermaidAPI.spec.js
  src/themes/dark/index.scss
Labels: Type: Enhancement

#1543 #1485 Setting proper font settings in the root css
  cypress/integration/other/webpackUsage.spec.js
  cypress/platform/bundle-test.js
  cypress/platform/webpackUsage.html
  dist/mermaid.core.js
  dist/mermaid.core.js.map
  dist/mermaid.js
  dist/mermaid.js.map
  dist/mermaid.min.js
  dist/mermaid.min.js.map
  docs/Setup.md
  src/mermaidAPI.js
  src/themes/mermaid.scss
  src/themes/pie.scss
Labels: Type: Bug / Error

#1549 #1454 Adding showcase diagrams rendered with the different themes
  cypress/integration/rendering/theme.spec.js
  cypress/platform/viewer.js
Labels: Type: Enhancement

#1561 #Beta flowchart: issues with edges to some types of nodes
  cypress/platform/bundle-test.js
  src/dagre-wrapper/intersect/intersect-polygon.js
Labels: Type: Bug / Error

#1566 #1552 Fix for broken cardinality support for class diagrams
  cypress/platform/current.html
  src/utils.js
Labels: Area: Development, Graph: Class

#1567 Feature/issue 1465 class migration
  cypress/platform/class.html
  src/dagre-wrapper/GraphObjects.md
  src/dagre-wrapper/edges.js
  src/dagre-wrapper/index.js
  src/dagre-wrapper/markers.js
  src/dagre-wrapper/nodes.js
  src/diagrams/class/classRenderer-v2.js
  src/diagrams/class/parser/classDiagram.jison
  src/diagrams/class/styles.js
  src/diagrams/flowchart/flowRenderer-v2.js
  src/diagrams/state/stateRenderer-v2.js
  src/mermaidAPI.js
  src/styles.js
  src/themes/class.scss
  src/utils.js
Labels: Type: Enhancement
