Repository mermaid-js/mermaid, pull requests merged in 2020-01, with the labels that each got.

#1136 Gantt: Add support for callback with parameters
  docs/gantt.md
  src/diagrams/gantt/ganttDb.js
  src/diagrams/gantt/parser/gantt.spec.js
Labels: Graph: Gantt, Type: Enhancement

#1167 Adding interaction tests for gantt callbacks with arguments
  cypress/integration/other/interaction.spec.js
  cypress/platform/click_security_loose.html
  cypress/platform/click_security_strict.html
Labels: Type: Enhancement

#1168 #834 Using & as a separator for the multiple nodes
  cypress/integration/rendering/flowchart.spec.js
  src/diagrams/flowchart/flowDb.js
  src/diagrams/flowchart/parser/flow-vertice-chaining.spec.js
  src/diagrams/flowchart/parser/flow.jison
  src/diagrams/flowchart/parser/subgraph.spec.js
Labels: Type: Enhancement

#1171 Feature/issue 1146 dashed line for class diagram
  cypress/integration/rendering/classDiagram.spec.js
  docs/classDiagram.md
  src/diagrams/class/classDiagram.spec.js
  src/diagrams/class/classRenderer.js
  src/themes/class.scss
Labels: Area: Development, Area: Documentation, Graph: Class, Type: Enhancement

#1178 1119 specify method return type in class diagram
  cypress/integration/rendering/classDiagram.spec.js
  docs/classDiagram.md
  src/diagrams/class/classDiagram.spec.js
  src/diagrams/class/classRenderer.js
Labels: Area: Development, Graph: Class, Type: Enhancement

#1207 #1205 Adding parsing exception for then an inactive participant is inactivated
  src/diagrams/sequence/sequenceDb.js
  src/diagrams/sequence/sequenceDiagram.spec.js
Labels: Type: Bug / Error

#1208 Feature/issue 1206 parsing crashing browser in class diagram
  src/diagrams/class/classDiagram.spec.js
  src/diagrams/class/parser/classDiagram.jison
Labels: Graph: Class, Status: Approved, Topic: Accessibility, Type: Bug / Error, Type: Enhancement

#1221 #1216 Fix for issue when mermaid freezes the browser tab due to large…
  cypress/platform/huge.html
  src/diagrams/flowchart/parser/flow-huge.spec.js
  src/mermaidAPI.js
Labels: Type: Bug / Error

#1229 #1217 Better matching of words beginning with as as matching token
  docs/mermaidAPI.md
  src/diagrams/state/parser/stateDiagram.jison
  src/diagrams/state/stateDiagram.spec.js
Labels: Type: Bug / Error

#1230 Bug/1223 multiple transitions in statediagram
  .gitignore
  cypress/integration/rendering/stateDiagram.spec.js
  cypress/platform/current.html
  src/diagrams/state/stateRenderer.js
Labels: Type: Bug / Error
