Repository mermaid-js/mermaid, pull requests merged in 2022-05, with the labels that each got.

#3002 GitGraph: add support for branch ordering
  src/diagrams/git/gitGraphAst.js
  src/diagrams/git/gitGraphParserV2.spec.js
  src/diagrams/git/parser/gitGraph.jison
Labels: feature

#3049 # Add support for cyclic themeVariable rotation when more than 8 branches
  cypress/integration/rendering/gitGraph.spec.js
  docs/gitgraph.md
  src/diagrams/git/gitGraphRenderer.js
Labels: ✔️ has tests

#3064 docs: fix capitalisation of well known technologies
  docs/README.md
  docs/Setup.md
  docs/diagrams-and-syntax-and-examples/flowchart.md
  docs/n00b-gettingStarted.md
  docs/usage.md
Labels: fix

#3063 feat: adding "Critical Region"/"Option" and "Break" blocks to sequence diagram
  cypress/integration/rendering/sequencediagram.spec.js
  docs/sequenceDiagram.md
  src/diagrams/sequence/parser/sequenceDiagram.jison
  src/diagrams/sequence/sequenceDb.js
  src/diagrams/sequence/sequenceDiagram.spec.js
  src/diagrams/sequence/sequenceRenderer.js
Labels: feature

#3092 Fix for case where a compound state has a transition to it self.
  cypress/integration/rendering/stateDiagram-v2.spec.js
  cypress/platform/knsv.html
  src/dagre-wrapper/edges.js
  src/dagre-wrapper/mermaid-graphlib.js
  src/dagre-wrapper/nodes.js
  src/utils.js
Labels: ✔️ has tests
