Repository mermaid-js/mermaid, pull requests merged in 2022-09, with the labels that each got.

#3396 fix: fix passing a single Node to mermaid.init()
  src/__mocks__/mermaidAPI.ts
  src/mermaid.spec.js
  src/mermaid.ts
Labels: fix

#3399 Added mermerd to integrations documentation
  docs/integrations.md
Labels: feature

#3415 Update duplicate copy pasted directive description
  docs/directives.md
  src/docs/directives.md
Labels: Area: Documentation

#3392 fix(git): support numeric branch names
  src/diagrams/git/gitGraphParserV2.spec.js
  src/diagrams/git/parser/gitGraph.jison
Labels: fix

#3422 chore: fix JSDOC @param, @returns lint errors
  src/assignWithDepth.js
  src/dagre-wrapper/mermaid-graphlib.js
  src/diagrams/c4/c4Renderer.js
  src/diagrams/class/classRenderer.js
  src/diagrams/er/erRenderer.js
  src/diagrams/flowchart/flowRenderer.js
  src/diagrams/git/gitGraphRenderer.js
  src/diagrams/mindmap/mindmapRenderer.js
  src/diagrams/sequence/sequenceRenderer.js
  src/diagrams/state/shapes.js
  src/setupGraphViewbox.js
Labels: chore

#3438 fix(git): support unusual prefixes in branch name
  src/diagrams/git/gitGraphParserV2.spec.js
  src/diagrams/git/parser/gitGraph.jison
Labels: fix

#3464 fix(git): support single character branch names
  src/diagrams/git/gitGraphParserV2.spec.js
  src/diagrams/git/parser/gitGraph.jison
Labels: Graph: Git, fix

#3459 Update Cypress to v10 and fix E2E errors
  .github/workflows/e2e
  .github/workflows/e2e.yml
  applitools.cnfig.js
  applitools.config.js
  cypress.config.js
  cypress/downloads/downloads.html
  cypress/helpers/util.js
  cypress/integration/other/configuration.spec.js
  cypress/integration/other/xss.spec.js
  cypress/integration/rendering/flowchart.spec.js
  cypress/integration/rendering/gitGraph.spec.js
  cypress/plugins/index.js
  cypress/support/e2e.js
  package.json
  src/dagre-wrapper/edges.js
  src/diagram-api/diagram-orchestration.ts
  yarn.lock
Labels: Area: DevOps, chore

#3480 Fix broken cherry-pick parsing in gitgraph
  src/diagrams/git/gitGraphParserV2.spec.js
  src/diagrams/git/parser/gitGraph.jison
Labels: Graph: Git, fix

#3479 feat(git): cherry-pick keyword supports tag attribute
  cypress/integration/rendering/gitGraph.spec.js
  docs/gitgraph.md
  src/diagrams/git/gitGraphAst.js
  src/diagrams/git/gitGraphParserV2.spec.js
  src/diagrams/git/parser/gitGraph.jison
Labels: Graph: Git, feature

#3483 ci(e2e-applitols): add applitools CI action
  .github/workflows/e2e-applitools.yml
Labels: Area: DevOps, github_actions

#3509 Add "Debug Current Test File" configuration for VSCode
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
Labels: feature

#3519 ci(e2e): fix e2e action when running from fork
  .github/workflows/e2e.yml
Labels: Area: DevOps, github_actions, bug

#3516 feat: ER diagram: allow other chars in a quoted entity name
  demos/er.html
  package.json
  src/diagrams/er/erRenderer.js
  src/diagrams/er/parser/erDiagram.jison
  src/diagrams/er/parser/erDiagram.spec.js
  yarn.lock
Labels: feature

#3524 [sequenceDiagrams] Support dashes in participant names
  src/diagrams/sequence/parser/sequenceDiagram.jison
  src/diagrams/sequence/sequenceDiagram.spec.js
Labels: feature

#3535 docs: replace `yarn` with `pnpm` in dev guide
  CONTRIBUTING.md
  docs/development.md
  packages/mermaid/src/docs/development.md
Labels: Area: Documentation, Area: DevOps

#3534 Fix `docs:build` and `docs:verify` scripts
  docs/8.6.0_docs.md
  docs/CHANGELOG.md
  docs/Configuration.md
  docs/README.md
  docs/SUMMARY.md
  docs/Setup.md
  docs/Tutorials.md
  docs/_navbar.md
  docs/_sidebar.md
  docs/accessibility.md
  docs/breakingChanges.md
  docs/c4c.md
  docs/classDiagram.md
  docs/developer-docs/configuration.md
  docs/development.md
  docs/diagrams-and-syntax-and-examples/flowchart.md
  docs/directives.md
  docs/entityRelationshipDiagram.md
  docs/examples.md
  docs/faq.md
  docs/flowchart.md
  docs/gantt.md
  docs/gitgraph.md
  docs/index.html
  docs/integrations.md
  docs/introduction.md
  docs/landing/index.html
  docs/mermaidCLI.md
  docs/mindmap.md
  docs/n00b-advanced.md
  docs/n00b-gettingStarted.md
  docs/n00b-overview.md
  docs/n00b-syntaxReference.md
  docs/newDiagram.md
  docs/pie.md
  docs/requirementDiagram.md
  docs/security.md
  docs/sequenceDiagram.md
  docs/stateDiagram.md
  docs/theming.md
  docs/upgrading.md
  docs/usage.md
  docs/user-journey.md
  packages/mermaid/src/docs.mts
Labels: Area: Documentation, Area: DevOps

#3536 Fix husky `pre-commit` rules
  .husky/pre-commit
  .lintstagedrc.json
  package.json
Labels: Area: DevOps
