Repository mermaid-js/mermaid, pull requests merged in 2022-10, with the labels that each got.

#3541 Corrected theme variables reference table layout
  docs/theming.md
  packages/mermaid/src/docs/theming.md
Labels: Area: Documentation

#3545 chore: Update demo diagrams for monorepo
  demos/c4context.html
  demos/classchart.html
  demos/dataflowchart.html
  demos/er.html
  demos/flowchart.html
  demos/gantt.html
  demos/git.html
  demos/index.html
  demos/journey.html
  demos/pie.html
  demos/requirements.html
  demos/sequence.html
  demos/state.html
Labels: chore

#3578 CODE_OF_CONDUCT Uploaded
  CODE_OF_CONDUCT.md
Labels: Area: Documentation

#3579 docs:Improved keywords in index.html
  .eslintrc.json
  __mocks__/dagre-d3.ts
  cypress/platform/xss10.html
  cypress/platform/xss11.html
  cypress/platform/xss12.html
  cypress/platform/xss13.html
  cypress/platform/xss14.html
  cypress/platform/xss15.html
  cypress/platform/xss16.html
  cypress/platform/xss17.html
  cypress/platform/xss18.html
  cypress/platform/xss19.html
  cypress/platform/xss2.html
  cypress/platform/xss20.html
  cypress/platform/xss21.html
  cypress/platform/xss3.html
  cypress/platform/xss4.html
  cypress/platform/xss5.html
  cypress/platform/xss6.html
  cypress/platform/xss7.html
  cypress/platform/xss8.html
  cypress/platform/xss9.html
  demos/c4context.html
  demos/dataflowchart.html
  demos/flowchart.html
  demos/gantt.html
  docs/Setup.md
  docs/classDiagram.md
  docs/diagrams-and-syntax-and-examples/flowchart.md
  docs/flowchart.md
  docs/gantt.md
  docs/index.html
  docs/usage.md
  packages/mermaid/src/docs/Setup.md
  packages/mermaid/src/docs/classDiagram.md
  packages/mermaid/src/docs/diagrams-and-syntax-and-examples/flowchart.md
  packages/mermaid/src/docs/flowchart.md
  packages/mermaid/src/docs/gantt.md
  packages/mermaid/src/docs/index.html
  packages/mermaid/src/docs/usage.md
  vdocs/config/Setup.md
  vdocs/config/usage.md
  vdocs/syntax/classDiagram.md
  vdocs/syntax/flowchart.md
  vdocs/syntax/gantt.md
Labels: Area: Documentation

#3596 docs: Add mermaid version to script URL
  README.md
  README.zh-CN.md
  docs/README.md
  docs/index.html
  docs/n00b-gettingStarted.md
  docs/usage.md
  package.json
  packages/mermaid/src/docs.mts
  packages/mermaid/src/docs/README.md
  packages/mermaid/src/docs/index.html
  packages/mermaid/src/docs/n00b-gettingStarted.md
  packages/mermaid/src/docs/usage.md
  pnpm-lock.yaml
  vdocs/config/usage.md
  vdocs/intro/index.md
  vdocs/intro/n00b-gettingStarted.md
Labels: Area: Documentation

#3679 Added Open Graph meta tags
  docs/index.html
  packages/mermaid/src/docs/index.html
Labels: Area: Documentation, feature

#3604 Added and configured cspell plugin to eslint
  .eslintrc.json
  cSpell.json
  cypress/helpers/util.js
  cypress/integration/rendering/appli.spec.js
  cypress/platform/xss21.html
  package.json
  packages/mermaid-example-diagram/src/detector.ts
  packages/mermaid-example-diagram/src/exampleDiagramRenderer.js
  packages/mermaid-mindmap/src/mindmapRenderer.js
  packages/mermaid/src/config.ts
  packages/mermaid/src/dagre-wrapper/edges.js
  packages/mermaid/src/dagre-wrapper/intersect/index.js
  packages/mermaid/src/dagre-wrapper/intersect/intersect-line.js
  packages/mermaid/src/dagre-wrapper/mermaid-graphlib.js
  packages/mermaid/src/dagre-wrapper/nodes.js
  packages/mermaid/src/defaultConfig.ts
  packages/mermaid/src/diagram-api/diagramAPI.ts
  packages/mermaid/src/diagrams/c4/c4Renderer.js
  packages/mermaid/src/diagrams/class/classDetector-V2.ts
  packages/mermaid/src/diagrams/class/classDetector.ts
  packages/mermaid/src/diagrams/class/classRenderer-v2.js
  packages/mermaid/src/diagrams/class/classRenderer.js
  packages/mermaid/src/diagrams/class/svgDraw.js
  packages/mermaid/src/diagrams/common/common.ts
  packages/mermaid/src/diagrams/er/erRenderer.js
  packages/mermaid/src/diagrams/flowchart/flowChartShapes.js
  packages/mermaid/src/diagrams/flowchart/flowDetector-v2.ts
  packages/mermaid/src/diagrams/flowchart/flowDetector.ts
  packages/mermaid/src/diagrams/flowchart/parser/flow-direction.spec.js
  packages/mermaid/src/diagrams/gantt/ganttDb.js
  packages/mermaid/src/diagrams/gantt/ganttRenderer.js
  packages/mermaid/src/diagrams/gantt/parser/gantt.spec.js
  packages/mermaid/src/diagrams/git/gitGraphAst.js
  packages/mermaid/src/diagrams/git/gitGraphRenderer-old.js
  packages/mermaid/src/diagrams/git/layout.js
  packages/mermaid/src/diagrams/info/infoRenderer.js
  packages/mermaid/src/diagrams/pie/pieRenderer.js
  packages/mermaid/src/diagrams/requirement/requirementRenderer.js
  packages/mermaid/src/diagrams/sequence/sequenceDiagram.spec.js
  packages/mermaid/src/diagrams/sequence/sequenceRenderer.ts
  packages/mermaid/src/diagrams/sequence/svgDraw.js
  packages/mermaid/src/diagrams/state/shapes.js
  packages/mermaid/src/diagrams/state/stateDetector.ts
  packages/mermaid/src/diagrams/state/stateRenderer-v2.js
  packages/mermaid/src/diagrams/state/stateRenderer.js
  packages/mermaid/src/diagrams/user-journey/journeyRenderer.ts
  packages/mermaid/src/diagrams/user-journey/svgDraw.js
  packages/mermaid/src/mermaidAPI.ts
  packages/mermaid/src/setupGraphViewbox.js
  packages/mermaid/src/themes/theme-base.js
  packages/mermaid/src/themes/theme-dark.js
  packages/mermaid/src/themes/theme-default.js
  packages/mermaid/src/themes/theme-forest.js
  packages/mermaid/src/themes/theme-neutral.js
  packages/mermaid/src/utils.ts
  pnpm-lock.yaml
Labels: feature

#3698 Chore/3697 eslint curly
  .eslintrc.json
  cypress/helpers/util.js
  cypress/platform/viewer.js
  packages/mermaid/src/dagre-wrapper/createLabel.js
  packages/mermaid/src/dagre-wrapper/edges.js
  packages/mermaid/src/dagre-wrapper/mermaid-graphlib.js
  packages/mermaid/src/dagre-wrapper/nodes.js
  packages/mermaid/src/defaultConfig.ts
  packages/mermaid/src/diagrams/c4/c4Db.js
  packages/mermaid/src/diagrams/c4/c4Renderer.js
  packages/mermaid/src/diagrams/c4/svgDraw.js
  packages/mermaid/src/diagrams/class/classDb.js
  packages/mermaid/src/diagrams/class/classDetector-V2.ts
  packages/mermaid/src/diagrams/class/classDetector.ts
  packages/mermaid/src/diagrams/class/svgDraw.js
  packages/mermaid/src/diagrams/common/common.ts
  packages/mermaid/src/diagrams/flowchart/flowChartShapes.js
  packages/mermaid/src/diagrams/flowchart/flowDb.js
  packages/mermaid/src/diagrams/flowchart/flowDetector-v2.ts
  packages/mermaid/src/diagrams/flowchart/flowDetector.ts
  packages/mermaid/src/diagrams/gantt/ganttDb.js
  packages/mermaid/src/diagrams/gantt/ganttRenderer.js
  packages/mermaid/src/diagrams/git/gitGraphAst.js
  packages/mermaid/src/diagrams/git/gitGraphRenderer-old.js
  packages/mermaid/src/diagrams/sequence/sequenceDb.js
  packages/mermaid/src/diagrams/sequence/sequenceRenderer.ts
  packages/mermaid/src/diagrams/sequence/svgDraw.js
  packages/mermaid/src/diagrams/state/shapes.js
  packages/mermaid/src/diagrams/state/stateDb.js
  packages/mermaid/src/diagrams/state/stateDetector-V2.ts
  packages/mermaid/src/diagrams/state/stateDetector.ts
  packages/mermaid/src/diagrams/state/stateRenderer.js
  packages/mermaid/src/diagrams/user-journey/journeyRenderer.ts
  packages/mermaid/src/mermaid.ts
  packages/mermaid/src/mermaidAPI.ts
  packages/mermaid/src/utils.ts
Labels: chore

#3707 Update sequenceDiagram.md
  docs/sequenceDiagram.md
  packages/mermaid/src/docs/sequenceDiagram.md
Labels: Area: Documentation

#3708 Use `eslint-plugin-tsdoc` for TypeScript files instead of `eslint-plugin-jsdoc`
  .eslintrc.json
  package.json
  packages/mermaid-example-diagram/src/detector.ts
  packages/mermaid-example-diagram/src/mermaidUtils.ts
  packages/mermaid/src/__mocks__/mermaidAPI.ts
  packages/mermaid/src/config.ts
  packages/mermaid/src/defaultConfig.ts
  packages/mermaid/src/diagram-api/detectType.ts
  packages/mermaid/src/diagrams/common/common.ts
  packages/mermaid/src/diagrams/error/errorRenderer.ts
  packages/mermaid/src/diagrams/sequence/sequenceRenderer.ts
  packages/mermaid/src/diagrams/user-journey/journeyRenderer.ts
  packages/mermaid/src/logger.ts
  packages/mermaid/src/mermaid.ts
  packages/mermaid/src/mermaidAPI.ts
  packages/mermaid/src/themes/erDiagram-oldHardcodedValues.ts
  packages/mermaid/src/utils.ts
  pnpm-lock.yaml
Labels: chore

#3702 Support `lazyLoadedDiagrams` when calling `initThrowsErrors`
  packages/mermaid/src/mermaid.spec.ts
  packages/mermaid/src/mermaid.ts
Labels: fix, bug

#3647 add the way to add notes to class diagram
  README.md
  cypress/integration/rendering/classDiagram-v2.spec.js
  cypress/integration/rendering/classDiagram.spec.js
  docs/classDiagram.md
  packages/mermaid/src/diagrams/class/classDb.js
  packages/mermaid/src/diagrams/class/classDiagram.spec.js
  packages/mermaid/src/diagrams/class/classRenderer-v2.js
  packages/mermaid/src/diagrams/class/classRenderer.js
  packages/mermaid/src/diagrams/class/parser/classDiagram.jison
  packages/mermaid/src/diagrams/class/styles.js
  packages/mermaid/src/diagrams/class/svgDraw.js
  packages/mermaid/src/docs/classDiagram.md
  packages/mermaid/src/utils.ts
Labels: feature

#3649 add statement aliases for ER diagram
  cypress/integration/rendering/erDiagram.spec.js
  docs/entityRelationshipDiagram.md
  packages/mermaid/src/diagrams/er/parser/erDiagram.jison
  packages/mermaid/src/diagrams/er/parser/erDiagram.spec.js
  packages/mermaid/src/docs/entityRelationshipDiagram.md
Labels: feature

#3719 Change fill attribute to style
  packages/mermaid/src/diagrams/er/erRenderer.js
Labels: fix

#3644 feat: [State diagram] Add classDefs and classes to states
  cSpell.json
  cypress/integration/rendering/stateDiagram-v2.spec.js
  demos/state.html
  docs/index.html
  packages/mermaid/src/diagrams/state/parser/state-style.spec.js
  packages/mermaid/src/diagrams/state/parser/stateDiagram.jison
  packages/mermaid/src/diagrams/state/stateCommon.ts
  packages/mermaid/src/diagrams/state/stateDb.js
  packages/mermaid/src/diagrams/state/stateDb.spec.js
  packages/mermaid/src/diagrams/state/stateDiagram-v2.spec.js
  packages/mermaid/src/diagrams/state/stateRenderer-v2.js
  packages/mermaid/src/docs/index.html
  packages/mermaid/src/mermaidAPI.ts
Labels: feature

#3612 docs: Add link to docs source
  docs/8.6.0_docs.md
  docs/CHANGELOG.md
  docs/Configuration.md
  docs/README.md
  docs/SUMMARY.md
  docs/Setup.md
  docs/Tutorials.md
  docs/_navbar.md
  docs/_sidebar.md
  docs/accessibility.md
  docs/breakingChanges.md
  docs/c4c.md
  docs/classDiagram.md
  docs/developer-docs/configuration.md
  docs/development.md
  docs/diagrams-and-syntax-and-examples/flowchart.md
  docs/directives.md
  docs/entityRelationshipDiagram.md
  docs/examples.md
  docs/faq.md
  docs/flowchart.md
  docs/gantt.md
  docs/gitgraph.md
  docs/index.html
  docs/integrations.md
  docs/introduction.md
  docs/landing/index.html
  docs/mermaidCLI.md
  docs/mindmap.md
  docs/n00b-advanced.md
  docs/n00b-gettingStarted.md
  docs/n00b-overview.md
  docs/n00b-syntaxReference.md
  docs/newDiagram.md
  docs/pie.md
  docs/requirementDiagram.md
  docs/security.md
  docs/sequenceDiagram.md
  docs/stateDiagram.md
  docs/theming.md
  docs/upgrading.md
  docs/usage.md
  docs/user-journey.md
  packages/mermaid/src/docs.mts
Labels: Area: Documentation
