Repository mermaid-js/mermaid, pull requests merged in 2022-04, with the labels that each got.

#2908 docs: adds alt text to images, corrects heading structure
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/Tutorials.md
  docs/developer-docs/configuration.md
Labels: feature

#2940 Fix example header: "A commit flow diagram."
  docs/examples.md
Labels: Type: Bug / Error, Area: Documentation

#2942 fix: no codeblock language
  docs/index.html
Labels: Type: Bug / Error

#2955 GitGraph. Support tags for merge commits
  src/diagrams/git/gitGraphAst.js
  src/diagrams/git/gitGraphParserV2.spec.js
  src/diagrams/git/parser/gitGraph.jison
Labels: feature

#2954 GitGraph: add support for "pathed" branches. fix #2936
  src/diagrams/git/gitGraphParserV2.spec.js
  src/diagrams/git/parser/gitGraph.jison
Labels: feature
