Repository mermaid-js/mermaid, pull requests merged in 2022-11, with the labels that each got.

#3729 feat(gantt): Add option 'tickInterval' for custom tick interval
  cypress/integration/rendering/gantt.spec.js
  docs/gantt.md
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/defaultConfig.ts
  packages/mermaid/src/diagrams/gantt/ganttDb.js
  packages/mermaid/src/diagrams/gantt/ganttRenderer.js
  packages/mermaid/src/diagrams/gantt/parser/gantt.jison
  packages/mermaid/src/docs/gantt.md
Labels: feature, hacktoberfest, hacktoberfest-accepted

#3722 Fix/convert attr to style in er graph
  packages/mermaid/src/diagrams/er/erRenderer.js
Labels: fix

#2739 Use issue templates and add diagram, theme and syntax proposal issue forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/diagram_proposal.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/syntax_proposal.yml
  .github/ISSUE_TEMPLATE/theme_proposal.yml
Labels: Area: DevOps

#3751 chore: fix cSpell word entry misspelling "mermiad" -> "mermaid"
  cSpell.json
  packages/mermaid/src/Diagram.ts
Labels: chore

#3760 Fix link relative links to documentation files
  README.md
Labels: Area: Documentation

#3768 [9.2] fix(mermaid): fix `mermaid.render` types
  packages/mermaid/src/mermaid.ts
  packages/mermaid/src/mermaidAPI.ts
Labels: fix, bug

#3767 [9.2] fix(mermaid): default mermaid back to CommonJS
  packages/mermaid/package.json
Labels: fix, bug

#3684 chore: clean up code in mermaidAPI render() and write specs/tests
  cSpell.json
  docs/config/setup/modules/mermaidAPI.md
  packages/mermaid/src/diagrams/flowchart/flowDb.js
  packages/mermaid/src/diagrams/flowchart/flowRenderer.js
  packages/mermaid/src/mermaidAPI.spec.js
  packages/mermaid/src/mermaidAPI.spec.ts
  packages/mermaid/src/mermaidAPI.ts
  packages/mermaid/src/tests/MockedD3.ts
  packages/mermaid/typedoc.json
Labels: chore

#3765 Add GHA that will check links + Fix broken links
  .github/workflows/link-checker.yml
  .lycheeignore
  CONTRIBUTING.md
  README.zh-CN.md
  docs/community/development.md
  docs/community/n00b-overview.md
  docs/community/security.md
  docs/config/8.6.0_docs.md
  docs/config/Tutorials.md
  docs/config/usage.md
  docs/intro/index.md
  docs/intro/n00b-gettingStarted.md
  docs/intro/n00b-syntaxReference.md
  docs/misc/integrations.md
  docs/syntax/examples.md
  docs/syntax/gantt.md
  docs/syntax/sequenceDiagram.md
  packages/mermaid/src/docs/community/development.md
  packages/mermaid/src/docs/community/n00b-overview.md
  packages/mermaid/src/docs/community/security.md
  packages/mermaid/src/docs/config/8.6.0_docs.md
  packages/mermaid/src/docs/config/Tutorials.md
  packages/mermaid/src/docs/config/usage.md
  packages/mermaid/src/docs/intro/index.md
  packages/mermaid/src/docs/intro/n00b-gettingStarted.md
  packages/mermaid/src/docs/intro/n00b-syntaxReference.md
  packages/mermaid/src/docs/misc/integrations.md
  packages/mermaid/src/docs/syntax/examples.md
  packages/mermaid/src/docs/syntax/gantt.md
  packages/mermaid/src/docs/syntax/sequenceDiagram.md
Labels: feature

#3735 CI: disable pinning dependencies
  package.json
  packages/mermaid-example-diagram/package.json
  packages/mermaid-mindmap/package.json
  packages/mermaid/package.json
  pnpm-lock.yaml
  renovate.json
Labels: Area: DevOps

#3807 Use `github-dark` to highlight fence blocks in vitepress docs
  packages/mermaid/package.json
  packages/mermaid/src/docs/.vitepress/config.ts
  packages/mermaid/src/docs/.vitepress/mermaid-markdown-all.ts
  pnpm-lock.yaml
Labels: Area: Documentation

#3706 feat: Title support via front matter for ER, state, class, git, and graph diagrams
  __mocks__/d3.ts
  cypress/integration/rendering/classDiagram-v2.spec.js
  cypress/integration/rendering/erDiagram.spec.js
  cypress/integration/rendering/flowchart-v2.spec.js
  cypress/integration/rendering/gitGraph.spec.js
  cypress/integration/rendering/stateDiagram-v2.spec.js
  demos/classchart.html
  demos/er.html
  demos/flowchart.html
  demos/git.html
  demos/journey.html
  demos/state.html
  docs/config/setup/modules/defaultConfig.md
  docs/syntax/classDiagram.md
  docs/syntax/entityRelationshipDiagram.md
  docs/syntax/flowchart.md
  docs/syntax/gitgraph.md
  docs/syntax/stateDiagram.md
  package.json
  packages/mermaid/src/Diagram.ts
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/defaultConfig.ts
  packages/mermaid/src/diagram-api/detectType.ts
  packages/mermaid/src/diagram-api/frontmatter.spec.ts
  packages/mermaid/src/diagram-api/frontmatter.ts
  packages/mermaid/src/diagram-api/types.ts
  packages/mermaid/src/diagrams/class/classDb.js
  packages/mermaid/src/diagrams/class/classRenderer-v2.js
  packages/mermaid/src/diagrams/class/styles.js
  packages/mermaid/src/diagrams/er/erDb.js
  packages/mermaid/src/diagrams/er/erRenderer.js
  packages/mermaid/src/diagrams/er/styles.js
  packages/mermaid/src/diagrams/flowchart/flowDb.js
  packages/mermaid/src/diagrams/flowchart/flowRenderer-v2.js
  packages/mermaid/src/diagrams/flowchart/styles.ts
  packages/mermaid/src/diagrams/git/gitGraphAst.js
  packages/mermaid/src/diagrams/git/gitGraphRenderer.js
  packages/mermaid/src/diagrams/git/styles.js
  packages/mermaid/src/diagrams/state/stateDb.js
  packages/mermaid/src/diagrams/state/stateRenderer-v2.js
  packages/mermaid/src/diagrams/state/styles.js
  packages/mermaid/src/docs/syntax/classDiagram.md
  packages/mermaid/src/docs/syntax/entityRelationshipDiagram.md
  packages/mermaid/src/docs/syntax/flowchart.md
  packages/mermaid/src/docs/syntax/gitgraph.md
  packages/mermaid/src/docs/syntax/stateDiagram.md
  packages/mermaid/src/utils.spec.js
  packages/mermaid/src/utils.ts
  pnpm-lock.yaml
Labels: feature, hacktoberfest-accepted

#3809 Replace `dagre`/`dagre-d3` with `dagre-d3-es`
  cypress/integration/rendering/mermaid.spec.js
  cypress/integration/rendering/mindmap.spec.js
  cypress/integration/rendering/mindmap.spec.ts
  cypress/tsconfig.json
  demos/index.html
  demos/mindmap.html
  package.json
  packages/mermaid/package.json
  packages/mermaid/src/dagre-wrapper/index.js
  packages/mermaid/src/dagre-wrapper/mermaid-graphlib.spec.js
  packages/mermaid/src/diagrams/class/classRenderer.js
  packages/mermaid/src/diagrams/er/erRenderer.js
  packages/mermaid/src/diagrams/flowchart/flowChartShapes.js
  packages/mermaid/src/diagrams/flowchart/flowRenderer-v2.js
  packages/mermaid/src/diagrams/flowchart/flowRenderer.js
  packages/mermaid/src/diagrams/requirement/requirementRenderer.js
  packages/mermaid/src/diagrams/state/stateRenderer.js
  packages/mermaid/src/tests/setup.ts
  pnpm-lock.yaml
Labels: dependencies

#3841 (feat) state classDef documentation
  demos/state.html
  docs/syntax/stateDiagram.md
  packages/mermaid/src/diagrams/pie/pieDetector.ts
  packages/mermaid/src/docs/syntax/stateDiagram.md
Labels: feature

#3861 chore(deps): remove dependency on `graphlib`
  packages/mermaid/package.json
  pnpm-lock.yaml
Labels: dependencies, chore

#3860 Make gitgraph snapshots consistent in E2E tests
  cypress/integration/rendering/gitGraph.spec.js
Labels: Graph: Git, Skip changelog, bug, chore

#3829 Use stylis to prepend idSelector
  packages/mermaid/src/mermaidAPI.ts
  packages/mermaid/src/styles.ts
Labels: fix
