Repository mermaid-js/mermaid, pull requests merged in 2022-12, with the labels that each got.

#3871 chore: delete functions not used in diagrams/c4 code (dead code)
  packages/mermaid/src/diagrams/c4/svgDraw.js
Labels: chore

#3899 doc: remove links from atom.io; add note Atom has been archived
  docs/misc/integrations.md
  packages/mermaid/src/docs/misc/integrations.md
Labels: Area: Documentation

#3897 feat: Set svg role to 'graphics-document document'
  packages/mermaid/src/accessibility.spec.ts
  packages/mermaid/src/accessibility.ts
Labels: Topic: Accessibility, feature

#3892 Adding support for parenthesis in the er diagram attribute types.
  cypress/integration/rendering/erDiagram.spec.js
  demos/er.html
  docs/syntax/entityRelationshipDiagram.md
  packages/mermaid/src/diagrams/er/parser/erDiagram.jison
  packages/mermaid/src/diagrams/er/parser/erDiagram.spec.js
  packages/mermaid/src/docs/syntax/entityRelationshipDiagram.md
Labels: feature, Graph: Entity Relationship

#3917 feat(er): add unique key
  demos/er.html
  docs/syntax/entityRelationshipDiagram.md
  packages/mermaid/src/diagrams/er/parser/erDiagram.jison
  packages/mermaid/src/diagrams/er/parser/erDiagram.spec.js
  packages/mermaid/src/docs/syntax/entityRelationshipDiagram.md
Labels: feature

#3920 docs(README.zh-CN): fix book image src
  README.zh-CN.md
  packages/mermaid/README.zh-CN.md
Labels: Area: Documentation

#3904 fix: dev server watch mode
  .vite/build.ts
Labels: Area: Documentation, fix

#3925 docs: fix typo
  docs/community/newDiagram.md
  packages/mermaid/src/docs/community/newDiagram.md
Labels: Area: Documentation

#3935 chore(pr): add documentation task in PR template
  .github/pull_request_template.md
Labels: chore

#3859 Support parsing indented mermaid/YAML only from HTML
  demos/classchart.html
  demos/er.html
  demos/flowchart.html
  demos/git.html
  demos/journey.html
  demos/state.html
  packages/mermaid/package.json
  packages/mermaid/src/diagram-api/diagram-orchestration.ts
  packages/mermaid/src/mermaid.ts
  packages/mermaid/src/mermaidAPI.spec.ts
  packages/mermaid/src/utils.spec.js
  pnpm-lock.yaml
Labels: dependencies, fix
