Repository mermaid-js/mermaid, pull requests merged in 2023-12, with the labels that each got.

#5104 build: use `tsx` instead of `ts-node-esm`
  .lintstagedrc.mjs
  .vscode/launch.json
  package.json
  packages/mermaid/package.json
  packages/mermaid/src/docs/package.json
  pnpm-lock.yaml
Labels: Type: Other, Area: DevOps

#5107 Docs: update Latest News section
  docs/news/announcements.md
  docs/news/blog.md
  packages/mermaid/src/docs/news/announcements.md
  packages/mermaid/src/docs/news/blog.md
Labels: Area: Documentation

#5102 fix: #5100 Add viewbox to sankey
  demos/sankey.html
  packages/mermaid/src/diagrams/sankey/sankeyRenderer.ts
  packages/mermaid/src/setupGraphViewbox.js
Labels: Type: Bug / Error, Area: Development, Internals: Renderer, fix, Graph: Sankey

#5116 feat: Track outbound links in docs site.
  packages/mermaid/src/docs/.vitepress/components/TopBar.vue
  packages/mermaid/src/docs/.vitepress/config.ts
Labels: Area: Documentation

#5126 Remove default properties before generating the config types
  packages/mermaid/scripts/create-types-from-json-schema.mts
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/schemas/config.schema.yaml
Labels: Type: Other

#5118 feat: Add diagramType to RenderResult and ParseResult
  docs/config/setup/interfaces/mermaidAPI.ParseOptions.md
  docs/config/setup/interfaces/mermaidAPI.ParseResult.md
  docs/config/setup/interfaces/mermaidAPI.RenderResult.md
  docs/config/setup/modules/mermaidAPI.md
  docs/config/usage.md
  packages/mermaid/src/docs/config/usage.md
  packages/mermaid/src/mermaid.ts
  packages/mermaid/src/mermaidAPI.spec.ts
  packages/mermaid/src/mermaidAPI.ts
Labels: Type: Enhancement, Breaking Change

#5086 feat #5042: Add `flowchart.maxEdges` config.
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/diagrams/flowchart/flowDb.js
  packages/mermaid/src/schemas/config.schema.yaml
Labels: Type: Enhancement, Graph: Flow

#5112 Docs: update Getting Started page
  docs/intro/getting-started.md
  packages/mermaid/src/docs/intro/getting-started.md
Labels: Area: Documentation

#5111 Added functionality to support style keyword
  cypress/integration/rendering/classDiagram-v2.spec.js
  docs/syntax/classDiagram.md
  packages/mermaid/src/dagre-wrapper/nodes.js
  packages/mermaid/src/diagrams/class/classDb.ts
  packages/mermaid/src/diagrams/class/classDiagram-styles.spec.js
  packages/mermaid/src/diagrams/class/classDiagram.spec.ts
  packages/mermaid/src/diagrams/class/classRenderer-v2.ts
  packages/mermaid/src/diagrams/class/classTypes.ts
  packages/mermaid/src/diagrams/class/parser/classDiagram.jison
  packages/mermaid/src/docs/syntax/classDiagram.md
Labels: Type: Enhancement, Graph: Class
