Repository mermaid-js/mermaid, pull requests merged in 2023-07, with the labels that each got.

#4502 Sankey diagrams
  __mocks__/sankeyRenderer.js
  cSpell.json
  cypress/integration/rendering/sankey.spec.ts
  demos/index.html
  demos/sankey.html
  docker-compose.yml
  docs/config/setup/modules/defaultConfig.md
  docs/syntax/sankey.md
  packages/mermaid/package.json
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/defaultConfig.ts
  packages/mermaid/src/diagram-api/diagram-orchestration.ts
  packages/mermaid/src/diagrams/sankey/parser/energy.csv
  packages/mermaid/src/diagrams/sankey/parser/sankey.jison
  packages/mermaid/src/diagrams/sankey/parser/sankey.spec.ts
  packages/mermaid/src/diagrams/sankey/sankeyDB.ts
  packages/mermaid/src/diagrams/sankey/sankeyDetector.ts
  packages/mermaid/src/diagrams/sankey/sankeyDiagram.ts
  packages/mermaid/src/diagrams/sankey/sankeyRenderer.ts
  packages/mermaid/src/diagrams/sankey/sankeyUtils.ts
  packages/mermaid/src/docs/.vitepress/config.ts
  packages/mermaid/src/docs/.vitepress/scripts/fetch-avatars.ts
  packages/mermaid/src/docs/.vitepress/scripts/fetch-contributors.ts
  packages/mermaid/src/docs/syntax/sankey.md
  packages/mermaid/src/rendering-util/uid.ts
  pnpm-lock.yaml
  run
Labels: Status: Approved, Area: Development, Status: In progress, Type: New Diagram, feature

#4466 Feature/1838 actor creation destruction
  cypress/integration/rendering/sequencediagram.spec.js
  docs/syntax/sequenceDiagram.md
  packages/mermaid/src/diagrams/sequence/parser/sequenceDiagram.jison
  packages/mermaid/src/diagrams/sequence/sequenceDb.js
  packages/mermaid/src/diagrams/sequence/sequenceDiagram.spec.js
  packages/mermaid/src/diagrams/sequence/sequenceRenderer.ts
  packages/mermaid/src/diagrams/sequence/svgDraw.js
  packages/mermaid/src/docs/syntax/sequenceDiagram.md
Labels: Graph: Sequence, Area: Development, feature

#4587 Remove double parsing
  packages/mermaid/src/diagrams/class/classRenderer.js
  packages/mermaid/src/diagrams/er/erRenderer.js
  packages/mermaid/src/diagrams/flowchart/flowRenderer.js
  packages/mermaid/src/diagrams/gantt/ganttRenderer.js
  packages/mermaid/src/diagrams/git/gitGraphRenderer-old.js
  packages/mermaid/src/diagrams/mindmap/mindmapRenderer.js
  packages/mermaid/src/diagrams/pie/pieRenderer.js
  packages/mermaid/src/diagrams/requirement/requirementRenderer.js
  packages/mermaid/src/diagrams/state/stateRenderer.js
  packages/mermaid/src/diagrams/timeline/timelineRenderer.ts
  packages/mermaid/src/diagrams/user-journey/journeyRenderer.ts
Labels: Area: Development, Internals: Renderer

#4595 Sankey: Remove duplicated examples
  docs/syntax/sankey.md
  packages/mermaid/src/defaultConfig.ts
  packages/mermaid/src/docs/syntax/sankey.md
Labels: Area: Documentation, fix

#4602 Make quadrant chart options TypeScript types optional
  packages/mermaid/src/config.spec.js
  packages/mermaid/src/config.spec.ts
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/diagrams/quadrant-chart/quadrantBuilder.ts
Labels: fix

#4599 Support docs:dev in docker
  packages/mermaid/package.json
  packages/mermaid/src/docs/package.json
  run
Labels: fix

#4112 Use JSON Schema to define and document `MermaidConfig`
  .eslintrc.cjs
  .github/workflows/lint.yml
  .prettierignore
  .vite/build.ts
  .vite/jsonSchemaPlugin.ts
  docs/config/setup/modules/defaultConfig.md
  package.json
  packages/mermaid/.lintstagedrc.mjs
  packages/mermaid/package.json
  packages/mermaid/scripts/create-types-from-json-schema.mts
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/defaultConfig.ts
  packages/mermaid/src/docs.mts
  packages/mermaid/src/docs/.vitepress/config.ts
  packages/mermaid/src/docs/.vitepress/mermaid-markdown-all.ts
  packages/mermaid/src/oldDefaultConfig.ts
  packages/mermaid/src/schemas/config.schema.yaml
  pnpm-lock.yaml
  vite.config.ts
Labels: Area: Documentation, Area: DevOps

#4577 Fixes support of the macro `ContainerQueue_Ext` for C4 diagrams definition.
  packages/mermaid/src/diagrams/c4/parser/c4Container.spec.js
  packages/mermaid/src/diagrams/c4/parser/c4Diagram.jison
Labels: Type: Bug / Error, fix

#4641 chore: remove unused `devDependency` on coveralls
  package.json
  packages/mermaid/package.json
  pnpm-lock.yaml
Labels: chore

#4640 Fix the "Edit this page on GitHub" link in Vitepress documentation for the Mermaid Config pages
  packages/mermaid/src/docs.mts
  packages/mermaid/src/docs.spec.ts
  packages/mermaid/src/docs/.vitepress/config.ts
Labels: Area: Documentation, Area: DevOps

#4612 Support MERMAID_RELEASE_VERSION in docs.
  .github/pull_request_template.md
  .github/workflows/build-docs.yml
  .vscode/launch.json
  docs/community/development.md
  packages/mermaid/package.json
  packages/mermaid/scripts/docs.cli.mts
  packages/mermaid/scripts/docs.mts
  packages/mermaid/scripts/docs.spec.ts
  packages/mermaid/scripts/update-release-version.mts
  packages/mermaid/src/docs/community/development.md
Labels: Area: Documentation, Area: DevOps

#4639 feat | Vertical branches in Git Diagram
  cypress/integration/rendering/gitGraph.spec.js
  docs/syntax/gitgraph.md
  packages/mermaid/src/diagrams/git/gitGraphRenderer.js
  packages/mermaid/src/diagrams/git/parser/gitGraph.jison
  packages/mermaid/src/docs/syntax/gitgraph.md
Labels: feature

#4660 Docs: Corrects name of C4 link
  docs/syntax/c4.md
  packages/mermaid/src/docs/.vitepress/config.ts
  packages/mermaid/src/docs/.vitepress/theme/redirect.ts
  packages/mermaid/src/docs/syntax/c4.md
Labels: Area: Documentation
