Repository mermaid-js/mermaid, pull requests merged in 2023-05, with the labels that each got.

#4206 Implement `package` on class diagram
  README.md
  cypress/integration/rendering/classDiagram-v2.spec.js
  docs/syntax/classDiagram.md
  packages/mermaid/src/diagrams/class/classDb.ts
  packages/mermaid/src/diagrams/class/classDiagram.spec.ts
  packages/mermaid/src/diagrams/class/classRenderer-v2.ts
  packages/mermaid/src/diagrams/class/classTypes.ts
  packages/mermaid/src/diagrams/class/parser/classDiagram.jison
  packages/mermaid/src/docs/syntax/classDiagram.md
Labels: feature

#4378 test: fix classDiagramGrammer unit test
  packages/mermaid/src/diagrams/class/classDiagramGrammar.spec.ts
Labels: chore

#4376 Fix missing `await` in usage document
  docs/config/usage.md
  packages/mermaid/src/docs/config/usage.md
Labels: Area: Documentation

#4374 Add integrations
  cSpell.json
  docs/ecosystem/integrations.md
  packages/mermaid/src/docs/ecosystem/integrations.md
Labels: Area: Documentation

#4383 Added support for quadrant chart
  cypress/integration/rendering/quadrantChart.spec.js
  demos/index.html
  demos/quadrantchart.html
  docs/config/setup/modules/defaultConfig.md
  docs/intro/index.md
  docs/syntax/quadrantChart.md
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/defaultConfig.ts
  packages/mermaid/src/diagram-api/diagram-orchestration.ts
  packages/mermaid/src/diagrams/quadrant-chart/parser/quadrant.jison
  packages/mermaid/src/diagrams/quadrant-chart/parser/quadrant.jison.spec.ts
  packages/mermaid/src/diagrams/quadrant-chart/quadrantBuilder.ts
  packages/mermaid/src/diagrams/quadrant-chart/quadrantDb.ts
  packages/mermaid/src/diagrams/quadrant-chart/quadrantDetector.ts
  packages/mermaid/src/diagrams/quadrant-chart/quadrantDiagram.ts
  packages/mermaid/src/diagrams/quadrant-chart/quadrantRenderer.ts
  packages/mermaid/src/docs/.vitepress/config.ts
  packages/mermaid/src/docs/intro/examples.md
  packages/mermaid/src/docs/syntax/quadrantChart.md
  packages/mermaid/src/themes/theme-base.js
  packages/mermaid/src/themes/theme-dark.js
  packages/mermaid/src/themes/theme-default.js
  packages/mermaid/src/themes/theme-forest.js
  packages/mermaid/src/themes/theme-neutral.js
Labels: feature

#4425 Fix broken `pnpm-lock.yaml` file to fix CI
  pnpm-lock.yaml
Labels: chore

#4426 Merge PR #4425 to `master` to fix uploading v10.2.0 docs to `mermaid.js.org` website
  .github/workflows/link-checker.yml
  package.json
  packages/mermaid/package.json
  packages/mermaid/src/docs/package.json
  pnpm-lock.yaml
Labels: Area: DevOps, chore
