Repository mermaid-js/mermaid, pull requests merged in 2023-10, with the labels that each got.

#4913 Commented out broken test
  cypress/integration/rendering/gantt.spec.js
Labels: Graph: Gantt, Skip changelog

#4889 making consitent config imports from diagramAPI
  packages/mermaid/src/dagre-wrapper/clusters.js
  packages/mermaid/src/dagre-wrapper/createLabel.js
  packages/mermaid/src/dagre-wrapper/edges.js
  packages/mermaid/src/dagre-wrapper/nodes.js
  packages/mermaid/src/dagre-wrapper/shapes/note.js
  packages/mermaid/src/dagre-wrapper/shapes/util.js
  packages/mermaid/src/diagram-api/diagramAPI.ts
  packages/mermaid/src/diagrams/c4/c4Db.js
  packages/mermaid/src/diagrams/c4/c4Renderer.js
  packages/mermaid/src/diagrams/class/classDb.ts
  packages/mermaid/src/diagrams/class/classRenderer-v2.ts
  packages/mermaid/src/diagrams/class/classRenderer.js
  packages/mermaid/src/diagrams/class/classTypes.ts
  packages/mermaid/src/diagrams/er/erDb.js
  packages/mermaid/src/diagrams/er/erRenderer.js
  packages/mermaid/src/diagrams/flowchart/flowDb.js
  packages/mermaid/src/diagrams/flowchart/flowDiagram-v2.ts
  packages/mermaid/src/diagrams/flowchart/flowRenderer-v2.js
  packages/mermaid/src/diagrams/flowchart/flowRenderer.js
  packages/mermaid/src/diagrams/flowchart/flowRenderer.spec.js
  packages/mermaid/src/diagrams/gantt/ganttDb.js
  packages/mermaid/src/diagrams/gantt/ganttRenderer.js
  packages/mermaid/src/diagrams/git/gitGraphAst.js
  packages/mermaid/src/diagrams/git/layout.js
  packages/mermaid/src/diagrams/mindmap/mindmapDb.js
  packages/mermaid/src/diagrams/mindmap/mindmapRenderer.js
  packages/mermaid/src/diagrams/pie/pie.spec.ts
  packages/mermaid/src/diagrams/pie/pieDb.ts
  packages/mermaid/src/diagrams/pie/pieRenderer.ts
  packages/mermaid/src/diagrams/quadrant-chart/quadrantDb.ts
  packages/mermaid/src/diagrams/quadrant-chart/quadrantRenderer.ts
  packages/mermaid/src/diagrams/requirement/requirementDb.js
  packages/mermaid/src/diagrams/requirement/requirementRenderer.js
  packages/mermaid/src/diagrams/sankey/sankeyDB.ts
  packages/mermaid/src/diagrams/sankey/sankeyRenderer.ts
  packages/mermaid/src/diagrams/sequence/sequenceDb.js
  packages/mermaid/src/diagrams/sequence/sequenceDiagram.spec.js
  packages/mermaid/src/diagrams/sequence/sequenceRenderer.ts
  packages/mermaid/src/diagrams/state/shapes.js
  packages/mermaid/src/diagrams/state/stateDb.js
  packages/mermaid/src/diagrams/state/stateRenderer-v2.js
  packages/mermaid/src/diagrams/state/stateRenderer.js
  packages/mermaid/src/diagrams/timeline/timelineRenderer.ts
  packages/mermaid/src/diagrams/user-journey/journeyDb.js
  packages/mermaid/src/diagrams/user-journey/journeyRenderer.ts
  packages/mermaid/src/rendering-util/selectSvgElement.ts
Labels: Type: Bug / Error

#4970 Replace rehype-mermaidjs with rehype-mermaid
  docs/ecosystem/integrations-community.md
  packages/mermaid/src/docs/ecosystem/integrations-community.md
Labels: Area: Documentation
