Repository mermaid-js/mermaid, pull requests merged in 2023-03, with the labels that each got.

#4145 Pie: Adding outer border, text position options
  cypress/integration/rendering/pie.spec.js
  demos/pie.html
  docs/config/setup/modules/defaultConfig.md
  docs/config/theming.md
  docs/syntax/pie.md
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/defaultConfig.ts
  packages/mermaid/src/diagrams/pie/pieRenderer.js
  packages/mermaid/src/diagrams/pie/styles.js
  packages/mermaid/src/docs/config/theming.md
  packages/mermaid/src/docs/syntax/pie.md
  packages/mermaid/src/themes/theme-base.js
  packages/mermaid/src/themes/theme-dark.js
  packages/mermaid/src/themes/theme-default.js
  packages/mermaid/src/themes/theme-forest.js
  packages/mermaid/src/themes/theme-neutral.js
Labels: feature

#4184 Update integrations.md to include Mermaid Flow Visual Editor
  docs/ecosystem/integrations.md
  packages/mermaid/src/docs/ecosystem/integrations.md
Labels: Area: Documentation

#4174 feat: expose the diagram api
  docs/config/setup/modules/mermaidAPI.md
  packages/mermaid/src/Diagram.ts
  packages/mermaid/src/mermaidAPI.ts
Labels: feature

#4187 Expose detectType function
  docs/config/usage.md
  packages/mermaid/src/docs/config/usage.md
  packages/mermaid/src/mermaid.ts
Labels: feature

#4230 docs: Remove repeated phrase
  docs/syntax/timeline.md
  packages/mermaid/src/docs/syntax/timeline.md
Labels: Area: Documentation

#4237 Fix typos in timeline docs
  docs/syntax/timeline.md
  packages/mermaid/src/docs/syntax/timeline.md
Labels: Area: Documentation

#4246 Fix hexagon node flowchart code example in docs
  docs/syntax/flowchart.md
  packages/mermaid/src/docs/syntax/flowchart.md
Labels: Area: Documentation

#4249 Remove inline-specifiers pnpm option from `.npmrc` file to avoid merge conflicts
  .npmrc
Labels: Area: Development

#4238 Implement repeating tasks
  cypress/integration/rendering/gantt.spec.js
  demos/gantt.html
  docs/config/setup/modules/defaultConfig.md
  docs/config/setup/modules/mermaidAPI.md
  docs/syntax/gantt.md
  packages/mermaid/src/commonDb.ts
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/defaultConfig.ts
  packages/mermaid/src/diagram-api/frontmatter.ts
  packages/mermaid/src/diagram-api/types.ts
  packages/mermaid/src/diagrams/gantt/ganttDb.js
  packages/mermaid/src/diagrams/gantt/ganttDb.spec.ts
  packages/mermaid/src/diagrams/gantt/ganttRenderer.js
  packages/mermaid/src/diagrams/gantt/parser/gantt.jison
  packages/mermaid/src/docs/syntax/gantt.md
  packages/mermaid/src/mermaidAPI.ts
Labels: feature

#4207 Fix broken Gantt `todayMarker` tests
  cypress/integration/rendering/gantt.spec.js
Labels: Graph: Gantt
