Repository mermaid-js/mermaid, pull requests merged in 2023-01, with the labels that each got.

#3964 docs: Remove duplicate example in ER-diagram documentation
  docs/syntax/entityRelationshipDiagram.md
  packages/mermaid/src/docs/syntax/entityRelationshipDiagram.md
Labels: Area: Documentation, Graph: Entity Relationship

#3960 Update sequenceDiagram.md to include line break
  docs/syntax/sequenceDiagram.md
  packages/mermaid/src/docs/syntax/sequenceDiagram.md
Labels: Area: Documentation, Graph: Sequence

#3973 ci: disable checking twitter links
  .lycheeignore
Labels: Area: Documentation, Area: DevOps

#3946 (chore) Docs: add tag to produce only a diagram, not code example
  packages/mermaid/src/docs.mts
  packages/mermaid/src/docs.spec.ts
Labels: chore

#3954 Support GitHub Flavored Markdown in markdown documentation
  docs/CHANGELOG.md
  docs/config/Tutorials.md
  docs/config/setup/modules/mermaidAPI.md
  docs/config/usage.md
  docs/intro/index.md
  docs/intro/n00b-gettingStarted.md
  docs/syntax/c4c.md
  docs/syntax/gantt.md
  packages/mermaid/package.json
  packages/mermaid/src/docs.mts
  pnpm-lock.yaml
Labels: Area: Documentation

#3962 Add support for YAML frontmatter in Markdown docs (used for Vitepress config)
  packages/mermaid/package.json
  packages/mermaid/src/docs.mts
  packages/mermaid/src/docs.spec.ts
  packages/mermaid/src/docs/syntax/flowchart.md
  pnpm-lock.yaml
Labels: Area: Documentation

#4030 feat(er): add multiple key constraints
  demos/er.html
  docs/syntax/entityRelationshipDiagram.md
  packages/mermaid/src/diagrams/er/erRenderer.js
  packages/mermaid/src/diagrams/er/parser/erDiagram.jison
  packages/mermaid/src/diagrams/er/parser/erDiagram.spec.js
  packages/mermaid/src/docs/syntax/entityRelationshipDiagram.md
Labels: feature

#4032 docs(readme): update broken twitter badge
  README.md
  README.zh-CN.md
Labels: Area: Documentation

#4035 build(lint): cache prettier on `pnpm run lint`
  .github/workflows/lint.yml
  package.json
Labels: Area: DevOps, Status: In progress
