Repository mermaid-js/mermaid, pull requests merged in 2023-02, with the labels that each got.

#3965 Add Box support in Sequence Diagrams
  cypress/integration/rendering/sequencediagram.spec.js
  demos/sequence.html
  docs/syntax/sequenceDiagram.md
  packages/mermaid/src/diagrams/sequence/parser/sequenceDiagram.jison
  packages/mermaid/src/diagrams/sequence/sequenceDb.js
  packages/mermaid/src/diagrams/sequence/sequenceDiagram.spec.js
  packages/mermaid/src/diagrams/sequence/sequenceRenderer.ts
  packages/mermaid/src/diagrams/sequence/svgDraw.js
  packages/mermaid/src/docs.mts
  packages/mermaid/src/docs/syntax/sequenceDiagram.md
Labels: Type: PR

#4057 Cache `eslint` in pre-commit script (makes `git commit` 5x faster)
  .lintstagedrc.mjs
  package.json
Labels: Area: DevOps, chore

#4073 build(lint:fix): cache eslint in pnpm run lint:fix
  package.json
Labels: Area: DevOps, chore

#4074 💄 section width now covers all tasks
  packages/mermaid/src/diagrams/user-journey/journeyRenderer.ts
  packages/mermaid/src/diagrams/user-journey/svgDraw.js
Labels: feature

#4153 Replace `moment-mini`/`moment` date library with `dayjs`
  .github/workflows/test.yml
  docs/syntax/gantt.md
  packages/mermaid/package.json
  packages/mermaid/src/diagrams/gantt/ganttDb.js
  packages/mermaid/src/diagrams/gantt/ganttDb.spec.ts
  packages/mermaid/src/diagrams/gantt/ganttRenderer.js
  packages/mermaid/src/docs/syntax/gantt.md
  packages/mermaid/src/logger.ts
  packages/mermaid/src/tests/util.ts
  pnpm-lock.yaml
Labels: chore
