Repository mermaid-js/mermaid, pull requests merged in 2023-11, with the labels that each got.

#5016 fix(flow): fix invalid ellipseText regex
  packages/mermaid/src/diagrams/flowchart/parser/flow-text.spec.js
  packages/mermaid/src/diagrams/flowchart/parser/flow.jison
Labels: Graph: Flow, fix

#4959 Docs: update latest news
  docs/news/announcements.md
  docs/news/blog.md
  packages/mermaid/src/docs/news/announcements.md
  packages/mermaid/src/docs/news/blog.md
Labels: Area: Documentation

#5014 Update XYChart's nav link in the docs template
  packages/mermaid/src/docs/.vitepress/config.ts
Labels: Area: Documentation

#4958 fix(tooltip): remove redundant scroll offset
  packages/mermaid/src/diagrams/flowchart/flowDb.js
Labels: fix

#5013 Fix - static class attributes are not rendered underlined
  packages/mermaid/src/diagrams/class/classTypes.spec.ts
  packages/mermaid/src/diagrams/class/classTypes.ts
Labels: Type: Bug / Error, Graph: Class

#4868 Use `release-drafter/release-drafter` GitHub Action to label our PRs
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/pr-labeler-config-validator.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-draft.yml
Labels: Type: Other, Area: DevOps

#4927 Bug/4912 GitGraph routing and colouring for merges and cherry-picks
  cypress/integration/rendering/gitGraph.spec.js
  demos/git.html
  packages/mermaid/src/diagrams/git/gitGraphRenderer.js
Labels: Type: Bug / Error

#5055 update testTimeout from 5 seconds to 10 seconds
  packages/mermaid/src/mermaid.spec.ts
Labels: Type: Bug / Error

#5050 Allow registered diagrams to be overridden.
  packages/mermaid/src/diagram-api/detectType.ts
  packages/mermaid/src/diagram-api/diagramAPI.ts
  packages/mermaid/src/diagram.spec.ts
  packages/mermaid/src/mermaid.ts
Labels: Type: Enhancement

#5063 fix: flowchart image without text
  packages/mermaid/src/dagre-wrapper/shapes/util.js
Labels: Type: Bug / Error

#4837 refactor: Unify the edgeMarker adding logic
  packages/mermaid/src/dagre-wrapper/edgeMarker.spec.ts
  packages/mermaid/src/dagre-wrapper/edgeMarker.ts
  packages/mermaid/src/dagre-wrapper/edges.js
  packages/mermaid/src/diagrams/flowchart/elk/flowRenderer-elk.js
Labels: Type: Other, Skip changelog

#4288 fix: Adjust piechart viewbox for mobile devices with small width
  cypress/integration/rendering/pie.spec.ts
  packages/mermaid/src/diagrams/pie/pieRenderer.ts
  packages/mermaid/src/setupGraphViewbox.js
Labels: Type: Bug / Error, Graph: Pie

#5041 Feature/4935 subgraph title margin config option
  cypress/integration/rendering/flowchart-v2.spec.js
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/dagre-wrapper/clusters.js
  packages/mermaid/src/dagre-wrapper/edges.js
  packages/mermaid/src/dagre-wrapper/index.js
  packages/mermaid/src/schemas/config.schema.yaml
  packages/mermaid/src/utils/subGraphTitleMargins.spec.ts
  packages/mermaid/src/utils/subGraphTitleMargins.ts
Labels: Type: Enhancement, Graph: Flow

#5076 fix: clean comments in text in getDiagramFromText API so flowchart works well
  docs/config/setup/modules/mermaidAPI.md
  packages/mermaid/src/mermaidAPI.spec.ts
  packages/mermaid/src/mermaidAPI.ts
Labels: Type: Bug / Error
