Repository mermaid-js/mermaid, pull requests merged in 2023-06, with the labels that each got.

#4334 Add `@mermaid-js/mermaid-zenuml` package for zenuml Integration
  .eslintignore
  .vite/build.ts
  .vite/server.ts
  cSpell.json
  cypress/integration/rendering/zenuml.spec.js
  cypress/platform/viewer.js
  demos/index.html
  demos/zenuml.html
  docs/syntax/img/zenuml-participant-annotators.png
  docs/syntax/zenuml.md
  package.json
  packages/mermaid-zenuml/README.md
  packages/mermaid-zenuml/package.json
  packages/mermaid-zenuml/src/detector.ts
  packages/mermaid-zenuml/src/mermaidUtils.ts
  packages/mermaid-zenuml/src/parser.ts
  packages/mermaid-zenuml/src/zenuml-definition.ts
  packages/mermaid-zenuml/src/zenumlRenderer.ts
  packages/mermaid-zenuml/tsconfig.json
  packages/mermaid/src/docs/.vitepress/config.ts
  packages/mermaid/src/docs/.vitepress/theme/mermaid.ts
  packages/mermaid/src/docs/syntax/img/zenuml-participant-annotators.png
  packages/mermaid/src/docs/syntax/zenuml.md
  packages/mermaid/src/setupGraphViewbox.js
  pnpm-lock.yaml
Labels: Type: New Diagram, feature

#4452 Restore classes on edges for elk
  cypress/integration/rendering/flowchart-elk.spec.js
  packages/mermaid/src/diagrams/flowchart/elk/flowRenderer-elk.js
Labels: feature

#4478 Support for development in Docker
  .gitignore
  CONTRIBUTING.md
  docker-compose.yml
  run
Labels: feature

#3814 chore: revise Contributing documentation
  .gitignore
  CONTRIBUTING.md
  cSpell.json
  docs/community/development.md
  packages/mermaid/src/docs/.vitepress/config.ts
  packages/mermaid/src/docs/community/development.md
Labels: Contributor needed, Area: Documentation

#4507 change REAMDME.md coverage from coveralls into codecov
  README.md
  README.zh-CN.md
Labels: Area: Documentation

#4540 fix(flowchart): apply style on doublecircle
  packages/mermaid/src/dagre-wrapper/nodes.js
Labels: fix

#4553 fix(flowchart): allow multiple vertices with style
  packages/mermaid/src/diagrams/flowchart/parser/flow-style.spec.js
  packages/mermaid/src/diagrams/flowchart/parser/flow.jison
Labels: fix

#4532 fix(class): keep members in namespace classes
  demos/classchart.html
  packages/mermaid/src/diagrams/class/classDb.ts
  packages/mermaid/src/diagrams/class/classDiagram.spec.ts
  packages/mermaid/src/diagrams/class/classRenderer-v2.ts
  packages/mermaid/src/diagrams/class/classTypes.ts
Labels: fix
