Repository mermaid-js/mermaid, pull requests merged in 2023-09, with the labels that each got.

#4803 [v11] Limit `MermaidConfig` enum TypesScript types to certain values
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/mermaidAPI.spec.ts
  packages/mermaid/src/schemas/config.schema.yaml
  packages/mermaid/src/utils.spec.ts
Labels: Type: Other, Breaking Change

#4801 fix: typos
  docs/community/code.md
  docs/community/development.md
  docs/community/docker-development.md
  docs/community/newDiagram.md
  docs/config/directives.md
  docs/config/usage.md
  docs/intro/getting-started.md
  docs/syntax/mindmap.md
  docs/syntax/quadrantChart.md
  docs/syntax/sankey.md
  docs/syntax/sequenceDiagram.md
  packages/mermaid/src/docs/community/code.md
  packages/mermaid/src/docs/community/development.md
  packages/mermaid/src/docs/community/docker-development.md
  packages/mermaid/src/docs/community/newDiagram.md
  packages/mermaid/src/docs/config/directives.md
  packages/mermaid/src/docs/config/usage.md
  packages/mermaid/src/docs/intro/getting-started.md
  packages/mermaid/src/docs/syntax/mindmap.md
  packages/mermaid/src/docs/syntax/quadrantChart.md
  packages/mermaid/src/docs/syntax/sankey.md
  packages/mermaid/src/docs/syntax/sequenceDiagram.md
Labels: Area: Documentation

#4776 fix(er): allow underscore as leading char
  demos/er.html
  docs/syntax/entityRelationshipDiagram.md
  packages/mermaid/src/diagrams/er/parser/erDiagram.jison
  packages/mermaid/src/diagrams/er/parser/erDiagram.spec.js
  packages/mermaid/src/docs/syntax/entityRelationshipDiagram.md
Labels: Graph: Entity Relationship, fix

#4804 Align arrows on sequence diagram
  packages/mermaid/src/diagrams/sequence/parser/sequenceDiagram.jison
  packages/mermaid/src/diagrams/sequence/sequenceDb.js
  packages/mermaid/src/diagrams/sequence/sequenceDiagram.spec.js
  packages/mermaid/src/diagrams/sequence/sequenceRenderer.ts
  packages/mermaid/src/diagrams/sequence/svgDraw.js
Labels: Type: Bug / Error, Graph: Sequence, Internals: Renderer

#4788 fix: Allow hollow markers on edges
  packages/mermaid/src/dagre-wrapper/edges.js
  packages/mermaid/src/dagre-wrapper/index.js
  packages/mermaid/src/dagre-wrapper/markers.js
  packages/mermaid/src/dagre-wrapper/mermaid-graphlib.js
  packages/mermaid/src/diagrams/class/styles.js
Labels: Graph: Class

#4805 fix: Add support for `~test Array~string~` back in Class
  packages/mermaid/src/diagrams/common/common.spec.ts
  packages/mermaid/src/diagrams/common/common.ts
Labels: Type: Bug / Error, Graph: Class, Area: Development

#4778 Added support for millisecond and second to gantt tickInterval
  cypress/integration/rendering/gantt.spec.js
  docs/syntax/gantt.md
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/diagrams/gantt/ganttRenderer.js
  packages/mermaid/src/docs/syntax/gantt.md
  packages/mermaid/src/schemas/config.schema.yaml
Labels: Type: Enhancement, Graph: Gantt, Area: Development, feature

#4759 Add directive support to all diagrams by preprocessing
  docs/config/setup/interfaces/mermaidAPI.ParseOptions.md
  docs/config/setup/interfaces/mermaidAPI.RenderResult.md
  docs/config/setup/modules/mermaidAPI.md
  packages/mermaid/src/Diagram.ts
  packages/mermaid/src/__mocks__/mermaidAPI.ts
  packages/mermaid/src/config.ts
  packages/mermaid/src/diagram-api/comments.ts
  packages/mermaid/src/diagram-api/diagramAPI.ts
  packages/mermaid/src/diagram-api/frontmatter.spec.ts
  packages/mermaid/src/diagram-api/frontmatter.ts
  packages/mermaid/src/diagram-api/types.ts
  packages/mermaid/src/diagrams/c4/c4Db.js
  packages/mermaid/src/diagrams/c4/c4Diagram.ts
  packages/mermaid/src/diagrams/c4/parser/c4Diagram.jison
  packages/mermaid/src/diagrams/class/classDb.ts
  packages/mermaid/src/diagrams/class/parser/classDiagram.jison
  packages/mermaid/src/diagrams/er/erDb.js
  packages/mermaid/src/diagrams/er/parser/erDiagram.jison
  packages/mermaid/src/diagrams/flowchart/flowDb.js
  packages/mermaid/src/diagrams/flowchart/parser/flow.jison
  packages/mermaid/src/diagrams/gantt/ganttDb.js
  packages/mermaid/src/diagrams/gantt/parser/gantt.jison
  packages/mermaid/src/diagrams/git/gitGraphAst.js
  packages/mermaid/src/diagrams/git/gitGraphParser.spec.js
  packages/mermaid/src/diagrams/git/gitGraphParserV2.spec.js
  packages/mermaid/src/diagrams/git/parser/gitGraph.jison
  packages/mermaid/src/diagrams/pie/parser/pie.jison
  packages/mermaid/src/diagrams/pie/pie.spec.ts
  packages/mermaid/src/diagrams/pie/pieDb.ts
  packages/mermaid/src/diagrams/pie/pieTypes.ts
  packages/mermaid/src/diagrams/quadrant-chart/parser/quadrant.jison
  packages/mermaid/src/diagrams/quadrant-chart/parser/quadrant.jison.spec.ts
  packages/mermaid/src/diagrams/quadrant-chart/quadrantDb.ts
  packages/mermaid/src/diagrams/requirement/parser/requirementDiagram.jison
  packages/mermaid/src/diagrams/requirement/requirementDb.js
  packages/mermaid/src/diagrams/sequence/parser/sequenceDiagram.jison
  packages/mermaid/src/diagrams/sequence/sequenceDb.js
  packages/mermaid/src/diagrams/sequence/sequenceDiagram.spec.js
  packages/mermaid/src/diagrams/sequence/sequenceDiagram.ts
  packages/mermaid/src/diagrams/state/parser/stateDiagram.jison
  packages/mermaid/src/diagrams/state/stateDb.js
  packages/mermaid/src/diagrams/state/stateDiagram-v2.spec.js
  packages/mermaid/src/diagrams/state/stateDiagram.spec.js
  packages/mermaid/src/diagrams/timeline/parser/timeline.jison
  packages/mermaid/src/diagrams/timeline/timeline.spec.js
  packages/mermaid/src/diagrams/timeline/timelineDb.js
  packages/mermaid/src/diagrams/user-journey/journeyDb.js
  packages/mermaid/src/diagrams/user-journey/parser/journey.jison
  packages/mermaid/src/directiveUtils.ts
  packages/mermaid/src/mermaidAPI.ts
  packages/mermaid/src/preprocess.ts
  packages/mermaid/src/utils.spec.ts
  packages/mermaid/src/utils.ts
  packages/mermaid/src/utils/sanitizeDirective.ts
Labels: Area: Development, Internals: Parser, Type: Performance

#4826 refactor: Fix typings in utils.ts
  cSpell.json
  package.json
  packages/mermaid/src/diagrams/quadrant-chart/quadrantBuilder.ts
  packages/mermaid/src/mermaid.ts
  packages/mermaid/src/types.ts
  packages/mermaid/src/utils.spec.ts
  packages/mermaid/src/utils.ts
Labels: Type: Other, Area: Development

#4819 Support ClassDefs in external diagrams
  docs/config/setup/interfaces/mermaidAPI.ParseOptions.md
  docs/config/setup/interfaces/mermaidAPI.RenderResult.md
  docs/config/setup/modules/mermaidAPI.md
  packages/mermaid/package.json
  packages/mermaid/src/diagram-api/diagram-orchestration.ts
  packages/mermaid/src/diagram-api/diagramAPI.spec.ts
  packages/mermaid/src/diagram-api/types.ts
  packages/mermaid/src/diagram.spec.ts
  packages/mermaid/src/diagrams/flowchart/elk/flowRenderer-elk.js
  packages/mermaid/src/diagrams/flowchart/flowRenderer-v2.js
  packages/mermaid/src/diagrams/flowchart/flowRenderer.js
  packages/mermaid/src/diagrams/state/stateRenderer-v2.js
  packages/mermaid/src/mermaid.spec.ts
  packages/mermaid/src/mermaidAPI.spec.ts
  packages/mermaid/src/mermaidAPI.ts
Labels: Type: Enhancement, Area: Development, Internals: Renderer

#4830 Fix: flowchartElk Arrow overlap
  packages/mermaid/src/dagre-wrapper/edges.js
  packages/mermaid/src/dagre-wrapper/markers.js
  packages/mermaid/src/diagrams/class/classRenderer-v2.ts
  packages/mermaid/src/diagrams/class/classTypes.ts
  packages/mermaid/src/diagrams/flowchart/elk/flowRenderer-elk.js
  packages/mermaid/src/types.ts
  packages/mermaid/src/utils/lineWithOffset.ts
Labels: Type: Bug / Error

#4825 Give markers unique id's per graph
  cypress/integration/rendering/marker_unique_id.spec.js
  cypress/platform/marker_unique_id.html
  packages/mermaid/src/dagre-wrapper/edges.js
  packages/mermaid/src/dagre-wrapper/index.js
  packages/mermaid/src/dagre-wrapper/markers.js
Labels: Area: Development, Internals: Renderer, fix

#4847 Wait for `marker_unique_id.html` E2E test to render before taking a screenshot
  cypress/platform/marker_unique_id.html
Labels: Skip changelog

#4846 Wait for `theme-directives.html` E2E test to render before taking a screenshot
  cypress/integration/rendering/conf-and-directives.spec.js
  cypress/platform/theme-directives.html
Labels: Skip changelog

#4857 chore(dev-deps): update `@typescript-eslint/*` plugins to v6 (major)
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
Labels: Skip changelog

#4859 chore: shorten `flow-huge.spec.js` test case using `.repeat`
  cypress/platform/huge.html
  packages/mermaid/src/diagrams/flowchart/parser/flow-huge.spec.js
Labels: Skip changelog

#4887 docs: fix typo
  docs/syntax/flowchart.md
  packages/mermaid/src/docs/syntax/flowchart.md
Labels: Area: Documentation

#4883 Update link for the Mermaid integration in JetBrains IDEs
  docs/ecosystem/integrations.md
  packages/mermaid/src/docs/ecosystem/integrations.md
Labels: Area: Documentation
