Repository mermaid-js/mermaid, pull requests merged in 2023-08, with the labels that each got.

#4689 chore: ts-ignore comment was misleading, JISON doesn't support types
  packages/mermaid/src/diagrams/c4/c4Diagram.ts
  packages/mermaid/src/diagrams/class/classDiagram-v2.ts
  packages/mermaid/src/diagrams/class/classDiagram.ts
  packages/mermaid/src/diagrams/flowchart/flowDiagram-v2.ts
  packages/mermaid/src/diagrams/flowchart/flowDiagram.ts
  packages/mermaid/src/diagrams/gantt/ganttDiagram.ts
  packages/mermaid/src/diagrams/git/gitGraphDiagram.ts
  packages/mermaid/src/diagrams/mindmap/mindmap-definition.ts
  packages/mermaid/src/diagrams/pie/pieDiagram.ts
  packages/mermaid/src/diagrams/quadrant-chart/parser/quadrant.jison.spec.ts
  packages/mermaid/src/diagrams/quadrant-chart/quadrantDiagram.ts
  packages/mermaid/src/diagrams/requirement/requirementDiagram.ts
  packages/mermaid/src/diagrams/sequence/sequenceDiagram.ts
  packages/mermaid/src/diagrams/state/stateDiagram-v2.ts
  packages/mermaid/src/diagrams/state/stateDiagram.ts
  packages/mermaid/src/diagrams/timeline/timeline-definition.ts
  packages/mermaid/src/diagrams/user-journey/journeyDiagram.ts
Labels: chore

#4715 Use our prettier config on the `packages/mermaid/src/config.type.ts` file
  packages/mermaid/scripts/create-types-from-json-schema.mts
  packages/mermaid/src/config.type.ts
Labels: chore

#4719 create `ParserDefinition` type
  packages/mermaid/src/diagram-api/diagramAPI.spec.ts
  packages/mermaid/src/diagram-api/types.ts
  packages/mermaid/src/mermaid.spec.ts
Labels: chore

#4718 standardized `error` diagram
  packages/mermaid/src/diagrams/error/errorDiagram.ts
  packages/mermaid/src/diagrams/error/errorRenderer.ts
  packages/mermaid/src/diagrams/error/styles.js
  packages/mermaid/src/styles.spec.ts
Labels: chore

#4697 fix: Remove triple parsing of diagrams
  docs/community/newDiagram.md
  docs/config/setup/modules/mermaidAPI.md
  packages/mermaid/src/Diagram.ts
  packages/mermaid/src/diagram-api/diagramAPI.ts
  packages/mermaid/src/diagrams/er/erRenderer.js
  packages/mermaid/src/diagrams/flowchart/elk/flowRenderer-elk.js
  packages/mermaid/src/diagrams/flowchart/flowRenderer-v2.js
  packages/mermaid/src/diagrams/flowchart/flowRenderer.js
  packages/mermaid/src/diagrams/sequence/sequenceDiagram.spec.js
  packages/mermaid/src/diagrams/sequence/sequenceRenderer.ts
  packages/mermaid/src/diagrams/state/stateRenderer-v2.js
  packages/mermaid/src/docs/community/newDiagram.md
  packages/mermaid/src/mermaidAPI.ts
Labels: Internals: Renderer, Type: Performance

#4717 convert `assignWithDepth` to TS
  packages/mermaid/src/assignWithDepth.ts
Labels: chore

#4724 convert `diagrams/common/svgDrawCommon.js` to ts
  packages/mermaid/src/diagrams/c4/svgDraw.js
  packages/mermaid/src/diagrams/common/common.spec.ts
  packages/mermaid/src/diagrams/common/common.ts
  packages/mermaid/src/diagrams/common/commonTypes.ts
  packages/mermaid/src/diagrams/common/svgDrawCommon.js
  packages/mermaid/src/diagrams/common/svgDrawCommon.ts
  packages/mermaid/src/diagrams/sequence/sequenceRenderer.ts
  packages/mermaid/src/diagrams/sequence/svgDraw.js
  packages/mermaid/src/diagrams/user-journey/svgDraw.js
Labels: chore

#4729 Use ESBuild (replaces UMD with IIFE bundle)
  .build/common.ts
  .build/jisonTransformer.ts
  .build/jsonSchema.ts
  .esbuild/build.ts
  .esbuild/jisonPlugin.ts
  .esbuild/jsonSchemaPlugin.ts
  .esbuild/server.ts
  .esbuild/util.ts
  .vite/build.ts
  .vite/jisonPlugin.ts
  .vite/jsonSchemaPlugin.ts
  cSpell.json
  cypress/integration/other/iife.spec.js
  cypress/integration/other/webpackUsage.spec.js
  cypress/platform/e2e.html
  cypress/platform/external-diagrams-example-diagram.html
  cypress/platform/iife.html
  cypress/platform/interaction.html
  cypress/platform/viewer.js
  cypress/platform/webpackUsage.html
  cypress/platform/xss.html
  demos/dev/example.html
  demos/pie.html
  docs/config/usage.md
  docs/intro/index.md
  docs/intro/n00b-gettingStarted.md
  docs/syntax/mindmap.md
  docs/syntax/timeline.md
  package.json
  packages/mermaid-example-diagram/package.json
  packages/mermaid/package.json
  packages/mermaid/src/schemas/config.schema.yaml
  pnpm-lock.yaml
Labels: Breaking Change

#4752 ci(release-drafter): add more release notes categories
  .github/release-drafter.yml
Labels: Type: Other, Area: DevOps

#4750 feat: Support config in frontmatter.
  cSpell.json
  cypress/integration/rendering/conf-and-directives.spec.js
  demos/er.html
  demos/flowchart.html
  docs/config/configuration.md
  docs/config/directives.md
  docs/config/setup/interfaces/mermaidAPI.ParseOptions.md
  docs/config/setup/interfaces/mermaidAPI.RenderResult.md
  docs/config/setup/modules/config.md
  docs/config/setup/modules/defaultConfig.md
  docs/config/setup/modules/mermaidAPI.md
  packages/mermaid/src/Diagram.ts
  packages/mermaid/src/assignWithDepth.ts
  packages/mermaid/src/config.spec.ts
  packages/mermaid/src/config.ts
  packages/mermaid/src/defaultConfig.ts
  packages/mermaid/src/diagram-api/frontmatter.spec.ts
  packages/mermaid/src/diagram-api/frontmatter.ts
  packages/mermaid/src/directiveUtils.ts
  packages/mermaid/src/docs/config/configuration.md
  packages/mermaid/src/docs/config/directives.md
  packages/mermaid/src/mermaidAPI.ts
  packages/mermaid/src/schemas/config.schema.yaml
  packages/mermaid/src/utils.ts
Labels: Type: Enhancement

#4748 feat(sankey): Show values
  demos/sankey.html
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/diagrams/sankey/sankeyDB.ts
  packages/mermaid/src/diagrams/sankey/sankeyRenderer.ts
  packages/mermaid/src/schemas/config.schema.yaml
Labels: Type: Enhancement

#4769 chore: Preview PRs with mermaid-live-editor on Netlify
  netlify.toml
  scripts/editor.bash
Labels: Type: Other, Area: DevOps

#4767 Docs/2910 Remove n00b and fix some docs
  docker-compose.yml
  docs/config/Tutorials.md
  docs/config/advanced.md
  docs/config/usage.md
  docs/intro/getting-started.md
  docs/intro/index.md
  docs/intro/syntax-reference.md
  packages/mermaid/src/docs/.vitepress/config.ts
  packages/mermaid/src/docs/.vitepress/theme/redirect.spec.ts
  packages/mermaid/src/docs/.vitepress/theme/redirect.ts
  packages/mermaid/src/docs/config/Tutorials.md
  packages/mermaid/src/docs/config/advanced.md
  packages/mermaid/src/docs/config/usage.md
  packages/mermaid/src/docs/intro/getting-started.md
  packages/mermaid/src/docs/intro/index.md
  packages/mermaid/src/docs/intro/syntax-reference.md
  pnpm-lock.yaml
Labels: Area: Documentation

#4758 feat(er): add entity name alias
  cypress/integration/rendering/erDiagram.spec.js
  demos/er.html
  docs/syntax/entityRelationshipDiagram.md
  packages/mermaid/src/diagrams/er/erDb.js
  packages/mermaid/src/diagrams/er/erRenderer.js
  packages/mermaid/src/diagrams/er/parser/erDiagram.jison
  packages/mermaid/src/diagrams/er/parser/erDiagram.spec.js
  packages/mermaid/src/docs/syntax/entityRelationshipDiagram.md
Labels: Type: Enhancement, Area: Development, Graph: Entity Relationship, feature

#4727 feat: add `@mermaid-js/parser` package and `info` langium parser
  .build/common.ts
  .build/generateLangium.ts
  .build/langium-cli.d.ts
  .esbuild/build.ts
  .esbuild/server.ts
  .eslintignore
  .gitignore
  .prettierignore
  .vite/build.ts
  .vite/server.ts
  cSpell.json
  package.json
  packages/mermaid-zenuml/src/parser.ts
  packages/mermaid/package.json
  packages/mermaid/src/Diagram.ts
  packages/mermaid/src/diagram-api/diagram-orchestration.ts
  packages/mermaid/src/diagram-api/diagramAPI.spec.ts
  packages/mermaid/src/diagram-api/types.ts
  packages/mermaid/src/diagram.spec.ts
  packages/mermaid/src/diagrams/common/populateCommonDb.ts
  packages/mermaid/src/diagrams/error/errorDiagram.ts
  packages/mermaid/src/diagrams/info/info.spec.ts
  packages/mermaid/src/diagrams/info/infoDb.ts
  packages/mermaid/src/diagrams/info/infoDiagram.ts
  packages/mermaid/src/diagrams/info/infoParser.ts
  packages/mermaid/src/diagrams/info/infoTypes.ts
  packages/mermaid/src/diagrams/info/parser/info.jison
  packages/mermaid/src/mermaid.spec.ts
  packages/parser/LICENSE
  packages/parser/README.md
  packages/parser/langium-config.json
  packages/parser/package.json
  packages/parser/src/index.ts
  packages/parser/src/language/chevrotainWrapper.ts
  packages/parser/src/language/common/common.langium
  packages/parser/src/language/common/commonLexer.ts
  packages/parser/src/language/common/commonMatcher.ts
  packages/parser/src/language/common/commonValueConverters.ts
  packages/parser/src/language/common/index.ts
  packages/parser/src/language/index.ts
  packages/parser/src/language/info/index.ts
  packages/parser/src/language/info/info.langium
  packages/parser/src/language/info/infoModule.ts
  packages/parser/src/language/info/infoTokenBuilder.ts
  packages/parser/src/parse.ts
  packages/parser/tests/info.test.ts
  packages/parser/tests/test-util.ts
  packages/parser/tsconfig.json
  pnpm-lock.yaml
  vite.config.ts
Labels: Breaking Change
