Repository mermaid-js/mermaid, pull requests merged in 2024-10, with the labels that each got.

#5914 fix: ban version v3.1.7 of DOMPurify
  .changeset/witty-rabbits-hunt.md
  packages/mermaid/package.json
  pnpm-lock.yaml
Labels: Type: Bug / Error

#5849 Updated the code to include nested namespaces for class diagrams
  .changeset/add-nested-namespaces.md
  cypress/integration/rendering/classDiagram-v2.spec.js
  demos/classchart.html
  packages/mermaid/src/diagrams/class/classDiagram.spec.ts
  packages/mermaid/src/diagrams/class/parser/classDiagram.jison
Labels: Type: Bug / Error

#5916 Added documentation about merging blocks horizontally (Resolves #5836)
  docs/syntax/block.md
  packages/mermaid/src/docs/syntax/block.md
Labels: Area: Documentation

#5925 chore: Split cypress tests locally
  .github/workflows/e2e-timings.yml
  .github/workflows/e2e.yml
  cypress.config.ts
  cypress/timings.json
  package.json
  pnpm-lock.yaml
Labels: Area: DevOps

#5937 Fix icon shape color for colored icons.
  .changeset/chilly-hotels-mix.md
  .changeset/heavy-cats-mate.md
  cypress/integration/rendering/iconShape.spec.ts
  cypress/platform/viewer.js
  packages/mermaid/src/rendering-util/rendering-elements/shapes/icon.ts
  packages/mermaid/src/rendering-util/rendering-elements/shapes/iconCircle.ts
  packages/mermaid/src/rendering-util/rendering-elements/shapes/iconRounded.ts
  packages/mermaid/src/rendering-util/rendering-elements/shapes/iconSquare.ts
Labels: Graph: Flow

#5924 Auto generate shape docs
  .build/common.ts
  .esbuild/build.ts
  .esbuild/util.ts
  docs/syntax/flowchart.md
  packages/mermaid/package.json
  packages/mermaid/scripts/docs.mts
  packages/mermaid/scripts/docs.spec.ts
  packages/mermaid/scripts/loadHook.mjs
  packages/mermaid/src/docs/syntax/flowchart.md
Labels: Area: Documentation, Area: DevOps

#5951 docs(architecture): update icon name for database in exemple
  docs/syntax/architecture.md
  packages/mermaid/src/docs/syntax/architecture.md
Labels: Area: Documentation

#5957 Remove extraneous period
  docs/syntax/sequenceDiagram.md
  packages/mermaid/src/docs/syntax/sequenceDiagram.md
Labels: Area: Documentation

#5967 docs: bullet lists should not be code blocks
  docs/intro/syntax-reference.md
  packages/mermaid/src/docs/intro/syntax-reference.md
Labels: Area: Documentation

#5968 docs(integrations): fix listing order
  docs/ecosystem/integrations-community.md
  packages/mermaid/src/docs/ecosystem/integrations-community.md
Labels: Area: Documentation

#5918 docs: Fix inconsistency in Block Diagram doc example
  docs/syntax/block.md
  packages/mermaid/src/docs/syntax/block.md
Labels: Area: Documentation

#5972 docs(ecosystem): Add Zed extension zed-mermaid
  docs/ecosystem/integrations-community.md
  packages/mermaid/src/docs/ecosystem/integrations-community.md
Labels: Area: Documentation

#6002 fix: make `mermaid.parse` throw an error on invalid shapes
  .changeset/thick-elephants-search.md
  packages/mermaid/src/diagrams/flowchart/flowDb.ts
  packages/mermaid/src/diagrams/flowchart/parser/flow-node-data.spec.js
  packages/mermaid/src/diagrams/flowchart/types.ts
  packages/mermaid/src/rendering-util/rendering-elements/nodes.ts
  packages/mermaid/src/rendering-util/rendering-elements/shapes.ts
  packages/mermaid/src/rendering-util/types.ts
Labels: Type: Bug / Error, Graph: Flow

#6009 chore: update changeset for #5880
  .changeset/polite-rules-rescue.md
Labels: Type: Other, Area: Documentation, Area: DevOps
