Repository mermaid-js/mermaid, pull requests merged in 2024-01, with the labels that each got.

#4941 fix/1294_exhaustive-clear-sequenceDb-variables
  .npmrc
  cypress/helpers/util.ts
  cypress/integration/rendering/sequencediagram.spec.js
  docs/syntax/sequenceDiagram.md
  packages/mermaid/src/diagrams/sequence/sequenceDb.js
  packages/mermaid/src/docs/syntax/sequenceDiagram.md
  packages/mermaid/src/utils/imperativeState.spec.ts
  packages/mermaid/src/utils/imperativeState.ts
Labels: Type: Bug / Error, Graph: Sequence, fix

#5197 Revert 5041 feature/4935 subgraph title margin config option
  cypress/integration/rendering/flowchart-v2.spec.js
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/dagre-wrapper/clusters.js
  packages/mermaid/src/dagre-wrapper/edges.js
  packages/mermaid/src/dagre-wrapper/index.js
  packages/mermaid/src/schemas/config.schema.yaml
  packages/mermaid/src/utils/subGraphTitleMargins.spec.ts
  packages/mermaid/src/utils/subGraphTitleMargins.ts
Labels: Type: Enhancement

#5198 Revert "fix: render the participants in same order as they are created"
  demos/sequence.html
  packages/mermaid/src/diagrams/sequence/sequenceRenderer.ts
  packages/mermaid/src/diagrams/sequence/svgDraw.js
Labels: Type: Bug / Error

#5192 Updated gantt chart docs to show all config options
  docs/syntax/gantt.md
  packages/mermaid/src/docs/syntax/gantt.md
Labels: Area: Documentation, Graph: Gantt

#5132 Contribution documentation improvements
  .github/pull_request_template.md
  .gitignore
  CONTRIBUTING.md
  Dockerfile
  README.md
  README.zh-CN.md
  docker-compose.yml
  docker-entrypoint.sh
  docs/community/code.md
  docs/community/contributing.md
  docs/community/development.md
  docs/community/docker-development.md
  docs/community/documentation.md
  docs/community/intro.md
  docs/community/new-diagram.md
  docs/community/questions-and-suggestions.md
  docs/config/advanced.md
  docs/config/usage.md
  docs/ecosystem/img/python-mermaid-integration.png
  docs/ecosystem/tutorials.md
  docs/intro/getting-started.md
  docs/intro/index.md
  packages/mermaid/scripts/docs.mts
  packages/mermaid/src/docs/.vitepress/config.ts
  packages/mermaid/src/docs/.vitepress/theme/redirect.spec.ts
  packages/mermaid/src/docs/.vitepress/theme/redirect.ts
  packages/mermaid/src/docs/community/code.md
  packages/mermaid/src/docs/community/contributing.md
  packages/mermaid/src/docs/community/development.md
  packages/mermaid/src/docs/community/docker-development.md
  packages/mermaid/src/docs/community/documentation.md
  packages/mermaid/src/docs/community/intro.md
  packages/mermaid/src/docs/community/new-diagram.md
  packages/mermaid/src/docs/community/questions-and-suggestions.md
  packages/mermaid/src/docs/config/advanced.md
  packages/mermaid/src/docs/config/usage.md
  packages/mermaid/src/docs/ecosystem/img/python-mermaid-integration.png
  packages/mermaid/src/docs/ecosystem/integrations-community.md
  packages/mermaid/src/docs/ecosystem/integrations-create.md
  packages/mermaid/src/docs/ecosystem/mermaid-chart.md
  packages/mermaid/src/docs/ecosystem/tutorials.md
  packages/mermaid/src/docs/intro/getting-started.md
  packages/mermaid/src/docs/intro/index.md
  packages/mermaid/src/docs/syntax/flowchart.md
  pnpm-lock.yaml
  run
Labels: Area: Documentation

#5205 Revert "Revert 5041 feature/4935 subgraph title margin config option"
  cypress/integration/rendering/flowchart-v2.spec.js
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/dagre-wrapper/clusters.js
  packages/mermaid/src/dagre-wrapper/edges.js
  packages/mermaid/src/dagre-wrapper/index.js
  packages/mermaid/src/schemas/config.schema.yaml
  packages/mermaid/src/utils/subGraphTitleMargins.spec.ts
  packages/mermaid/src/utils/subGraphTitleMargins.ts
Labels: Type: Enhancement

#5066 Docs/4974 reorder integration links
  docs/ecosystem/integrations-community.md
  packages/mermaid/src/docs/ecosystem/integrations-community.md
Labels: Area: Documentation

#5127 Bug/5059 fix external connection after updating edges
  cypress/integration/rendering/flowchart-v2.spec.js
  packages/mermaid/src/dagre-wrapper/mermaid-graphlib.js
Labels: Type: Bug / Error

#5161 Feature/5114 add parallel commit config
  cypress/integration/rendering/gitGraph.spec.js
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/diagrams/git/gitGraphRenderer.js
  packages/mermaid/src/schemas/config.schema.yaml
Labels: Type: Enhancement

#4839 feat: Add packet diagram
  .build/jsonSchema.ts
  .esbuild/build.ts
  __mocks__/c4Renderer.js
  __mocks__/classRenderer-v2.js
  __mocks__/classRenderer.js
  __mocks__/dagre-d3.ts
  __mocks__/entity-decode/browser.ts
  __mocks__/erRenderer.js
  __mocks__/flowRenderer-v2.js
  __mocks__/ganttRenderer.js
  __mocks__/gitGraphRenderer.js
  __mocks__/journeyRenderer.js
  __mocks__/pieRenderer.ts
  __mocks__/requirementRenderer.js
  __mocks__/sankeyRenderer.js
  __mocks__/sequenceRenderer.js
  __mocks__/stateRenderer-v2.js
  cypress/integration/rendering/packet.spec.ts
  demos/dev/example.html
  demos/index.html
  demos/packet.html
  docs/config/setup/modules/defaultConfig.md
  docs/syntax/packet.md
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/defaultConfig.ts
  packages/mermaid/src/diagram-api/diagram-orchestration.ts
  packages/mermaid/src/diagram-api/types.ts
  packages/mermaid/src/diagrams/packet/db.ts
  packages/mermaid/src/diagrams/packet/detector.ts
  packages/mermaid/src/diagrams/packet/diagram.ts
  packages/mermaid/src/diagrams/packet/packet.spec.ts
  packages/mermaid/src/diagrams/packet/parser.ts
  packages/mermaid/src/diagrams/packet/renderer.ts
  packages/mermaid/src/diagrams/packet/styles.ts
  packages/mermaid/src/diagrams/packet/types.ts
  packages/mermaid/src/docs/.vitepress/config.ts
  packages/mermaid/src/docs/syntax/packet.md
  packages/mermaid/src/mermaidAPI.spec.ts
  packages/mermaid/src/schemas/config.schema.yaml
  packages/mermaid/src/styles.spec.ts
  packages/mermaid/src/themes/theme-dark.js
  packages/mermaid/src/themes/theme-forest.js
  packages/mermaid/src/types.ts
  packages/parser/langium-config.json
  packages/parser/src/index.ts
  packages/parser/src/language/index.ts
  packages/parser/src/language/packet/index.ts
  packages/parser/src/language/packet/module.ts
  packages/parser/src/language/packet/packet.langium
  packages/parser/src/language/packet/tokenBuilder.ts
  packages/parser/src/parse.ts
  scripts/editor.bash
Labels: Type: Enhancement, Area: Development, Type: New Diagram

#5160 [Fix] Sequence diagram actor menu popup
  cypress/integration/rendering/sequencediagram.spec.js
  demos/sequence.html
  packages/mermaid/src/diagrams/sequence/svgDraw.js
Labels: Type: Bug / Error

#5095 Changes to Gantt Parsers to allow hashes and semicolons to titles, sections, and task data.
  cypress/integration/rendering/gantt.spec.js
  demos/gantt.html
  packages/mermaid/src/diagrams/gantt/parser/gantt.jison
  packages/mermaid/src/diagrams/gantt/parser/gantt.spec.js
Labels: Graph: Gantt, Internals: Parser

#5233 refactor: Support async parsers [internal]
  packages/mermaid/src/Diagram.ts
  packages/mermaid/src/diagram-api/diagramAPI.spec.ts
  packages/mermaid/src/diagram-api/types.ts
  packages/mermaid/src/diagram.spec.ts
  packages/mermaid/src/diagrams/info/info.spec.ts
  packages/mermaid/src/diagrams/info/infoParser.ts
  packages/mermaid/src/diagrams/packet/packet.spec.ts
  packages/mermaid/src/diagrams/packet/parser.ts
  packages/mermaid/src/diagrams/sequence/sequenceDiagram.spec.js
  packages/mermaid/src/mermaidAPI.ts
  packages/parser/src/parse.ts
Labels: Area: Development, Internals: Parser, Breaking Change

#5236 fix: Dompurify Hooks
  packages/mermaid/src/diagrams/common/common.ts
Labels: Type: Bug / Error

#5250 fix: Redirect of old URLs
  packages/mermaid/package.json
  packages/mermaid/src/docs/.vitepress/theme/index.ts
  packages/mermaid/src/docs/.vitepress/theme/redirect.spec.ts
  packages/mermaid/src/docs/.vitepress/theme/redirect.ts
  packages/mermaid/src/docs/package.json
  pnpm-lock.yaml
Labels: Type: Bug / Error

#5241 Feature/4653 add actor-top class to sequence diagram
  cypress/integration/rendering/sequencediagram.spec.js
  docs/syntax/sequenceDiagram.md
  packages/mermaid/src/diagrams/sequence/svgDraw.js
  packages/mermaid/src/docs/syntax/sequenceDiagram.md
Labels: Type: Enhancement

#5254 chore: Add interface naming Convention
  .eslintrc.cjs
  packages/mermaid/src/diagrams/quadrant-chart/quadrantBuilder.ts
Labels: Type: Other
