Repository mermaid-js/mermaid, pull requests merged in 2024-07, with the labels that each got.

#5607 chore: Update @zenuml/core dependency to version 3.23.27
  packages/mermaid-zenuml/package.json
  pnpm-lock.yaml
Labels: Type: Other

#5625 fix(class): #5624 Reset direction to default in classDiagram
  packages/mermaid/src/diagrams/class/classDb.ts
  packages/mermaid/src/diagrams/class/classDiagram.spec.ts
Labels: Type: Bug / Error

#5640 docs: fix the classDef example in stateDiagram not display as code block, and long text display overflows
  docs/syntax/stateDiagram.md
  packages/mermaid/src/docs/syntax/stateDiagram.md
Labels: Area: Documentation

#5649 fix: double space in wrapped sequence diagram messages
  packages/mermaid/src/utils.ts
Labels: Type: Bug / Error

#5647 feat(3801): Multiple Tags support for Git Graph
  cypress/integration/rendering/gitGraph.spec.js
  packages/mermaid/src/diagrams/git/gitGraphAst.js
  packages/mermaid/src/diagrams/git/gitGraphParserV2.spec.js
  packages/mermaid/src/diagrams/git/gitGraphRenderer.js
  packages/mermaid/src/diagrams/git/parser/gitGraph.jison
  scripts/editor.bash
Labels: Type: Bug / Error
