Repository mermaid-js/mermaid, pull requests merged in 2024-05, with the labels that each got.

#5503 feat(state): add from, to ids for edge
  packages/mermaid/src/diagrams/class/classRenderer-v2.ts
  packages/mermaid/src/diagrams/flowchart/flowRenderer-v2.js
  packages/mermaid/src/diagrams/flowchart/flowRenderer.js
  packages/mermaid/src/diagrams/state/stateRenderer-v2.js
  packages/mermaid/src/utils.ts
Labels: Type: Enhancement

#5519 DOCS: Add blog post - Documentation Software
  docs/news/blog.md
  packages/mermaid/src/docs/news/blog.md
Labels: Area: Documentation

#5518 [PR#5468] refactor: remove TypeScript non null assertions
  docs/config/setup/modules/mermaidAPI.md
  packages/mermaid/src/diagrams/block/blockDB.ts
  packages/mermaid/src/diagrams/class/classDb.ts
  packages/mermaid/src/diagrams/class/classRenderer-v2.ts
  packages/mermaid/src/diagrams/flowchart/flowDb.ts
  packages/mermaid/src/diagrams/git/gitGraphAst.js
  packages/mermaid/src/diagrams/git/gitGraphParserV2.spec.js
  packages/mermaid/src/diagrams/pie/pieRenderer.ts
  packages/mermaid/src/diagrams/requirement/requirementRenderer.js
  packages/mermaid/src/diagrams/sankey/sankeyDB.ts
  packages/mermaid/src/diagrams/sequence/sequenceDb.ts
  packages/mermaid/src/diagrams/state/stateDb.js
  packages/mermaid/src/mermaidAPI.ts
Labels: Type: Other
