Repository mermaid-js/mermaid, pull requests merged in 2024-03, with the labels that each got.

#5345 build(deps): update `langium` to `v3` and apply the required changes
  package.json
  packages/parser/package.json
  packages/parser/src/language/info/module.ts
  packages/parser/src/language/packet/module.ts
  packages/parser/src/language/pie/module.ts
  pnpm-lock.yaml
Labels: Breaking Change

#5350 Vendor docs CSS dependencies
  packages/mermaid/src/docs/.vitepress/theme/custom.css
  packages/mermaid/src/docs/package.json
  pnpm-lock.yaml
Labels: Area: Documentation, Area: DevOps, Skip changelog

#5235 Calculate package size diff on PRs
  .github/workflows/e2e.yml
  package.json
  pnpm-lock.yaml
  scripts/size.ts
Labels: Area: DevOps, Skip changelog

#5365 ci(e2e): avoid commenting on PRs in CI, fixing PRs from forks
  .github/workflows/e2e.yml
Labels: Area: DevOps, Skip changelog

#5370 docs(integrations): update link to Mermaid app for Slack
  docs/ecosystem/integrations-community.md
  packages/mermaid/src/docs/ecosystem/integrations-community.md
Labels: Area: Documentation

#5376 feat: Make the examples interactive in the documentation site
  packages/mermaid/scripts/docs.mts
  packages/mermaid/src/docs/.vitepress/mermaid-markdown-all.ts
  packages/mermaid/src/docs/.vitepress/theme/Mermaid.vue
Labels: Area: Documentation

#5400 DOCS: Add Press Release
  docs/news/announcements.md
  docs/news/blog.md
  packages/mermaid/src/docs/news/announcements.md
  packages/mermaid/src/docs/news/blog.md
Labels: Area: Documentation

#5358 Feature/4661 gantt customize days of weekend
  cypress/integration/rendering/gantt.spec.js
  docs/syntax/gantt.md
  packages/mermaid/src/diagrams/gantt/ganttDb.js
  packages/mermaid/src/diagrams/gantt/ganttDb.spec.ts
  packages/mermaid/src/diagrams/gantt/parser/gantt.jison
  packages/mermaid/src/docs/syntax/gantt.md
Labels: Type: Enhancement

#5309 bug/5133 sequence diagram fix arrow corner
  packages/mermaid/src/diagrams/sequence/svgDraw.js
Labels: Type: Bug / Error

#5272 Feature/5245 sequence diagram add classes to actors text
  cypress/integration/rendering/sequencediagram.spec.js
  docs/syntax/sequenceDiagram.md
  packages/mermaid/src/diagrams/sequence/svgDraw.js
  packages/mermaid/src/docs/syntax/sequenceDiagram.md
Labels: Type: Enhancement

#4359 Add `suppressErrorRendering` option to avoid inserting 'Syntax error' message to DOM directly
  cypress/integration/other/configuration.spec.js
  cypress/platform/suppressError.html
  docs/config/setup/modules/mermaidAPI.md
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/mermaidAPI.ts
  packages/mermaid/src/schemas/config.schema.yaml
Labels: Type: Bug / Error

#4844 Fixed styling for lines for ELK flowchart
  cypress/integration/rendering/flowchart-elk.spec.js
  packages/mermaid-flowchart-elk/src/diagram-definition.ts
  packages/mermaid-flowchart-elk/src/flowRenderer-elk.js
Labels: Type: Bug / Error

#4856 Bug/4391 make markdown auto wrapping optional
  .husky/pre-commit
  cypress/integration/rendering/flowchart-v2.spec.js
  docs/config/setup/modules/config.md
  docs/syntax/flowchart.md
  packages/mermaid/src/config.ts
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/dagre-wrapper/clusters.js
  packages/mermaid/src/dagre-wrapper/edges.js
  packages/mermaid/src/dagre-wrapper/shapes/util.js
  packages/mermaid/src/diagrams/common/common.ts
  packages/mermaid/src/diagrams/mindmap/svgDraw.ts
  packages/mermaid/src/docs/syntax/flowchart.md
  packages/mermaid/src/rendering-util/createText.ts
  packages/mermaid/src/rendering-util/handle-markdown-text.spec.ts
  packages/mermaid/src/rendering-util/handle-markdown-text.ts
  packages/mermaid/src/schemas/config.schema.yaml
Labels: Type: Bug / Error

#5183 Flowchart: Apply `nodeSpacing`/`rankSpacing` config to subgraphs
  cypress/integration/rendering/flowchart-v2.spec.js
  demos/flowchart.html
  packages/mermaid/src/dagre-wrapper/index.js
Labels: Type: Bug / Error, Graph: Flow

#5259 feat(git-graph): GitGraph Bottom-to-Top Orientation
  cypress/integration/rendering/gitGraph.spec.js
  demos/git.html
  docs/syntax/gitgraph.md
  packages/mermaid/src/diagrams/git/gitGraphParser.spec.js
  packages/mermaid/src/diagrams/git/gitGraphRenderer.js
  packages/mermaid/src/diagrams/git/parser/gitGraph.jison
  packages/mermaid/src/docs/syntax/gitgraph.md
Labels: Type: Enhancement

#5425 DOCS: add Turing machine blog post
  docs/news/blog.md
  packages/mermaid/src/docs/news/blog.md
Labels: Area: Documentation
