Repository mermaid-js/mermaid, pull requests merged in 2024-08, with the labels that each got.

#5305 Fix Requirement overflow
  packages/mermaid/src/diagrams/requirement/requirementRenderer.js
Labels: Type: Bug / Error

#5723 refactor!(git): default to `useMaxWidth` true
  docs/config/setup/modules/defaultConfig.md
  packages/mermaid/src/defaultConfig.ts
Labels: Type: Bug / Error, Type: Other, Graph: Git, Breaking Change

#5724 refactor!(sankey): default to `useMaxWidth` true
  docs/config/setup/modules/defaultConfig.md
  packages/mermaid/src/defaultConfig.ts
Labels: Type: Bug / Error, Type: Other, Graph: Sankey, Breaking Change

#5664 Feature/4401 creating langium parser git graph
  .changeset/dirty-mails-watch.md
  packages/mermaid/src/diagrams/git/gitGraph.spec.ts
  packages/mermaid/src/diagrams/git/gitGraphAst.js
  packages/mermaid/src/diagrams/git/gitGraphAst.ts
  packages/mermaid/src/diagrams/git/gitGraphDiagram.ts
  packages/mermaid/src/diagrams/git/gitGraphParser.spec.js
  packages/mermaid/src/diagrams/git/gitGraphParser.ts
  packages/mermaid/src/diagrams/git/gitGraphParserV2.spec.js
  packages/mermaid/src/diagrams/git/gitGraphRenderer.js
  packages/mermaid/src/diagrams/git/gitGraphRenderer.ts
  packages/mermaid/src/diagrams/git/gitGraphTypes.ts
  packages/mermaid/src/diagrams/git/parser/gitGraph.jison
  packages/mermaid/tsconfig.json
  packages/parser/langium-config.json
  packages/parser/src/language/gitGraph/gitGraph.langium
  packages/parser/src/language/gitGraph/index.ts
  packages/parser/src/language/gitGraph/module.ts
  packages/parser/src/language/gitGraph/tokenBuilder.ts
  packages/parser/src/language/index.ts
  packages/parser/src/parse.ts
  packages/parser/tests/gitGraph.test.ts
  packages/parser/tests/test-util.ts
Labels: Type: Enhancement

#5766 fix: correct target branch for scorecard
  .github/workflows/scorecard.yml
Labels: Type: Bug / Error
