Repository mermaid-js/mermaid, pull requests merged in 2024-11, with the labels that each got.

#6038 Fix for intersection issue
  .changeset/fresh-bears-doubt.md
  cypress/platform/knsv2.html
  packages/mermaid/src/rendering-util/rendering-elements/shapes/tiltedCylinder.ts
Labels: Graph: Flow

#6079 fix: update dompurify to `^3.2.1` and remove `@types/dompurify`
  .changeset/neat-rabbits-bake.md
  packages/mermaid/package.json
  packages/mermaid/src/diagrams/common/common.ts
  packages/mermaid/src/mermaidAPI.ts
  pnpm-lock.yaml
  scripts/tsc-check.ts
Labels: Type: Bug / Error, Type: Other

#6064 Fix: edge case causing extreme height in Architecture Diagrams
  .changeset/angry-bags-brake.md
  cypress/integration/rendering/architecture.spec.ts
  packages/mermaid/src/diagrams/architecture/architectureDb.ts
  packages/mermaid/src/diagrams/architecture/architectureRenderer.ts
  packages/mermaid/src/diagrams/architecture/architectureTypes.ts
Labels: Type: Bug / Error

#6090 Hotfix/elk 0.1.7
  .changeset/hungry-guests-drive.md
  cypress/integration/rendering/flowchart-elk.spec.js
  cypress/platform/knsv2.html
  packages/mermaid-layout-elk/src/render.ts
Labels: Type: Bug / Error
