Repository mermaid-js/mermaid, pull requests merged in 2024-02, with the labels that each got.

#5221 Adding new diagram type - Block Diagram
  .vite/jsonSchemaPlugin.ts
  cypress/integration/rendering/block.spec.ts
  cypress/platform/knsv2.html
  demos/block.html
  demos/index.html
  docs/config/setup/modules/mermaidAPI.md
  docs/syntax/block.md
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/dagre-wrapper/blockArrowHelper.ts
  packages/mermaid/src/dagre-wrapper/createLabel.js
  packages/mermaid/src/dagre-wrapper/edges.js
  packages/mermaid/src/dagre-wrapper/nodes.js
  packages/mermaid/src/dagre-wrapper/shapes/util.js
  packages/mermaid/src/diagram-api/diagram-orchestration.ts
  packages/mermaid/src/diagrams/block/blockDB.ts
  packages/mermaid/src/diagrams/block/blockDetector.ts
  packages/mermaid/src/diagrams/block/blockDiagram.ts
  packages/mermaid/src/diagrams/block/blockRenderer.ts
  packages/mermaid/src/diagrams/block/blockTypes.ts
  packages/mermaid/src/diagrams/block/blockUtils.ts
  packages/mermaid/src/diagrams/block/layout.spec.ts
  packages/mermaid/src/diagrams/block/layout.ts
  packages/mermaid/src/diagrams/block/parser/block.jison
  packages/mermaid/src/diagrams/block/parser/block.spec.ts
  packages/mermaid/src/diagrams/block/renderHelpers.ts
  packages/mermaid/src/diagrams/block/styles.ts
  packages/mermaid/src/diagrams/flowchart/elk/flowRenderer-elk.js
  packages/mermaid/src/diagrams/flowchart/flowRenderer-v2.js
  packages/mermaid/src/diagrams/flowchart/parser/flow.spec.js
  packages/mermaid/src/docs/.vitepress/config.ts
  packages/mermaid/src/docs/syntax/block.md
  packages/mermaid/src/mermaidAPI.ts
  packages/mermaid/src/schemas/config.schema.yaml
  packages/mermaid/src/styles.spec.ts
Labels: Type: New Diagram

#5257 Bump @zenuml/core and update render options in mermaid-zenuml
  packages/mermaid-zenuml/package.json
  packages/mermaid-zenuml/src/zenumlRenderer.ts
  pnpm-lock.yaml
Labels: Type: Enhancement

#5167 xychart: support for multiple datasets added
  cypress/integration/rendering/xyChart.spec.js
  demos/xychart.html
  docs/syntax/xyChart.md
  packages/mermaid/src/diagrams/xychart/chartBuilder/components/plot/PlotType.ts
  packages/mermaid/src/diagrams/xychart/chartBuilder/components/plot/barPlot.ts
  packages/mermaid/src/diagrams/xychart/chartBuilder/components/plot/index.ts
  packages/mermaid/src/diagrams/xychart/chartBuilder/components/plot/linePlot.ts
  packages/mermaid/src/diagrams/xychart/chartBuilder/interfaces.ts
  packages/mermaid/src/diagrams/xychart/parser/xychart.jison.spec.ts
  packages/mermaid/src/diagrams/xychart/xychartDb.ts
  packages/mermaid/src/docs/syntax/xyChart.md
Labels: Type: Enhancement

#5287 Add new extension to integrations
  docs/ecosystem/integrations-community.md
  packages/mermaid/src/docs/ecosystem/integrations-community.md
Labels: Area: Documentation

#5322 Update recommended Vitest extension
  .vscode/extensions.json
Labels: Type: Other

#5304 Replace version number placeholder
  packages/mermaid/src/docs/syntax/gantt.md
Labels: Area: Documentation

#5336 Add gitgraph parallel commits to docs
  docs/syntax/gitgraph.md
  packages/mermaid/src/docs/syntax/gitgraph.md
Labels: Type: Other

#5333 Added link to Blazorade Mermaid to the community integrations page.
  packages/mermaid/src/docs/ecosystem/integrations-community.md
Labels: Area: Documentation

#5224 Implement "until" keyword in gantt charts
  cypress/integration/rendering/gantt.spec.js
  docs/syntax/gantt.md
  packages/mermaid/src/diagrams/gantt/ganttDb.js
  packages/mermaid/src/diagrams/gantt/ganttDb.spec.ts
  packages/mermaid/src/diagrams/gantt/parser/gantt.spec.js
  packages/mermaid/src/docs/syntax/gantt.md
Labels: Type: Enhancement

#5344 Resolves E2E testing issues and issue #5343
  cypress/integration/rendering/gitGraph.spec.js
Labels: Skip changelog
