Repository mermaid-js/mermaid, pull requests merged in 2024-06, with the labels that each got.

#5566 Fixed entrypoint path
  docker-compose.yml
Labels: Type: Bug / Error

#5573 docs: fix node version in CONTRIBUTING.md
  docs/community/contributing.md
  packages/mermaid/src/docs/community/contributing.md
Labels: Area: Documentation

#5579 Fixed wrong ELK detector
  packages/mermaid-flowchart-elk/src/detector.spec.ts
  packages/mermaid-flowchart-elk/src/detector.ts
Labels: Type: Bug / Error

#5564 Bug/5525 sequence diagram fix note z position
  cypress/integration/rendering/sequencediagram.spec.js
  packages/mermaid/src/diagrams/sequence/svgDraw.js
Labels: Type: Bug / Error

#5209 Feature/4051 sequence diagram multi directional arrow
  cypress/integration/rendering/sequencediagram.spec.js
  docs/syntax/sequenceDiagram.md
  packages/mermaid/src/diagrams/sequence/parser/sequenceDiagram.jison
  packages/mermaid/src/diagrams/sequence/sequenceDb.ts
  packages/mermaid/src/diagrams/sequence/sequenceDiagram.spec.js
  packages/mermaid/src/diagrams/sequence/sequenceRenderer.ts
  packages/mermaid/src/diagrams/sequence/svgDraw.js
  packages/mermaid/src/docs/syntax/sequenceDiagram.md
  packages/mermaid/src/mermaid.spec.ts
Labels: Type: Enhancement

#5556 [XYChart] fixed incorrect spacing between data points
  cypress/integration/rendering/xyChart.spec.js
  packages/mermaid/src/diagrams/xychart/xychartDb.ts
Labels: Type: Bug / Error

#5589 docs: Added demo diagram of bidirectional arrows for sequence diagrams
  demos/sequence.html
Labels: Area: Documentation

#5598 fix: prevent escaping label styles
  packages/mermaid/src/dagre-wrapper/createLabel.js
  packages/mermaid/src/rendering-util/createText.ts
Labels: Type: Bug / Error
