Repository mermaid-js/mermaid, pull requests merged in 2025-03, with the labels that each got.

#6381 feat: Add radar diagram
  .build/jsonSchema.ts
  .changeset/quick-news-enjoy.md
  cypress/integration/rendering/radar.spec.js
  demos/index.html
  demos/radar.html
  docs/community/contributing.md
  docs/config/setup/defaultConfig/variables/configKeys.md
  docs/config/setup/mermaid/interfaces/MermaidConfig.md
  docs/syntax/radar.md
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/defaultConfig.ts
  packages/mermaid/src/diagram-api/diagram-orchestration.ts
  packages/mermaid/src/diagrams/radar/db.ts
  packages/mermaid/src/diagrams/radar/detector.ts
  packages/mermaid/src/diagrams/radar/diagram.ts
  packages/mermaid/src/diagrams/radar/parser.ts
  packages/mermaid/src/diagrams/radar/radar.spec.ts
  packages/mermaid/src/diagrams/radar/renderer.ts
  packages/mermaid/src/diagrams/radar/styles.ts
  packages/mermaid/src/diagrams/radar/types.ts
  packages/mermaid/src/diagrams/sequence/sequenceDiagram.spec.js
  packages/mermaid/src/docs/.vitepress/config.ts
  packages/mermaid/src/docs/community/contributing.md
  packages/mermaid/src/docs/syntax/radar.md
  packages/mermaid/src/mermaidAPI.spec.ts
  packages/mermaid/src/schemas/config.schema.yaml
  packages/mermaid/src/styles.spec.ts
  packages/mermaid/src/themes/theme-base.js
  packages/mermaid/src/themes/theme-dark.js
  packages/mermaid/src/themes/theme-default.js
  packages/mermaid/src/themes/theme-forest.js
  packages/mermaid/src/themes/theme-neutral.js
  packages/parser/langium-config.json
  packages/parser/src/language/index.ts
  packages/parser/src/language/radar/index.ts
  packages/parser/src/language/radar/module.ts
  packages/parser/src/language/radar/radar.langium
  packages/parser/src/language/radar/tokenBuilder.ts
  packages/parser/src/parse.ts
  packages/parser/tests/packet.test.ts
  packages/parser/tests/radar.test.ts
  packages/parser/tests/test-util.ts
Labels: Type: Enhancement

#6408 fix: restore curve type configuration functionality for flowcharts
  .changeset/curve-interpolation-fix.md
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/diagrams/flowchart/flowDb.spec.ts
  packages/mermaid/src/diagrams/flowchart/flowDb.ts
  packages/mermaid/src/rendering-util/rendering-elements/edges.js
  packages/mermaid/src/schemas/config.schema.yaml
Labels: Type: Bug / Error

#6410 test(e2e): fix Cypress config for Node.JS v20.19.0
  cypress.config.ts
Labels: Type: Other
