Repository mermaid-js/mermaid, pull requests merged in 2025-07, with the labels that each got.

#6707 4838: Log warning for duplicate commit IDs in gitGraph
  .changeset/full-donuts-give.md
  packages/mermaid/src/diagrams/git/gitGraph.spec.ts
  packages/mermaid/src/diagrams/git/gitGraphAst.ts
Labels: Graph: Git

#6718 Modify block diagram's logger to global log
  packages/mermaid/src/diagrams/block/blockDB.ts
Labels: Type: Enhancement

#6715 fix: update leftMargin value
  .changeset/wild-areas-lick.md
  packages/mermaid/src/diagrams/timeline/timelineRenderer.ts
Labels: fix, Graph: Timeline

#6747 6619: Prevent title from overlapping with box top border in Safari
  .changeset/tangy-ghosts-watch.md
  packages/mermaid/src/diagrams/sequence/svgDraw.js
Labels: Graph: Sequence, Sponsored by MermaidChart

#6756 chore: update katex to latest version due to CVE vulnerability
  packages/mermaid/package.json
  pnpm-lock.yaml
Labels: Type: Other

#6758 add noteshub.app to exclusions for certificate errors
  .github/lychee.toml
Labels: Type: Bug / Error, Sponsored by MermaidChart

#6717 6633: Log warning for blocks exceeding column width
  .changeset/ninety-roses-turn.md
  packages/mermaid/src/diagrams/block/blockDB.ts
  packages/mermaid/src/diagrams/block/parser/block.spec.ts
  packages/tiny/CHANGELOG.md
Labels: Graph: Block, Sponsored by MermaidChart

#6778 Update MIME type IANA status
  docs/ecosystem/integrations-create.md
  packages/mermaid/src/docs/ecosystem/integrations-create.md
Labels: Area: Documentation

#6702 Fix: Remove unexpected spaces in Block Diagram
  .changeset/lovely-queens-own.md
  cypress/integration/rendering/block.spec.js
  packages/mermaid/src/diagrams/block/layout.ts
Labels: Type: Bug / Error, Graph: Block

#6798 Fix: zenuml rendering
  .changeset/beige-peas-shave.md
  packages/mermaid-zenuml/README.md
  packages/mermaid-zenuml/package.json
  packages/mermaid-zenuml/src/zenuml.d.ts
  packages/mermaid-zenuml/src/zenumlRenderer.ts
  pnpm-lock.yaml
Labels: Type: Bug / Error

#6792 chore: Mermaid diagrams flowchart mindmap mermaid api
  docs/diagrams/flowchart-code-flow.mmd
  docs/diagrams/mermaid-api-sequence.mmd
  docs/diagrams/mindmap-implementation-sequence.mmd
  packages/mermaid/src/docs/diagrams/flowchart-code-flow.mmd
  packages/mermaid/src/docs/diagrams/mermaid-api-sequence.mmd
  packages/mermaid/src/docs/diagrams/mindmap-implementation-sequence.mmd
Labels: Sponsored by MermaidChart

#6796 make flowchart elk detector regex match less greedy
  .changeset/light-flowers-judge.md
  cypress/integration/rendering/classDiagram.spec.js
  cypress/integration/rendering/erDiagram.spec.js
  cypress/integration/rendering/mindmap.spec.ts
  packages/mermaid/src/diagram-api/diagram-orchestration.spec.ts
  packages/mermaid/src/diagrams/flowchart/elk/detector.ts
Labels: Type: Bug / Error

#6804 6691: update packet diagram to use new class-based DB approach
  .changeset/vast-buses-see.md
  packages/mermaid/src/diagrams/packet/db.ts
  packages/mermaid/src/diagrams/packet/diagram.ts
  packages/mermaid/src/diagrams/packet/packet.spec.ts
  packages/mermaid/src/diagrams/packet/parser.ts
Labels: Sponsored by MermaidChart
