Repository mermaid-js/mermaid, pull requests merged in 2025-09, with the labels that each got.

#6905 6780: treat newline characters as whitespace in class diagrams
  .changeset/clean-wolves-turn.md
  cypress/integration/rendering/classDiagram.spec.js
  packages/mermaid/src/diagrams/class/classDiagram.spec.ts
  packages/mermaid/src/diagrams/class/parser/classDiagram.jison
Labels: Graph: Class, Sponsored by MermaidChart

#6895 Docs(xychart): added plotcolorpalette example
  docs/syntax/xyChart.md
  packages/mermaid/src/docs/syntax/xyChart.md
Labels: Area: Documentation

#6913 Fix failing Cypress visual tests in mindmap diagrams
  cypress/integration/rendering/mindmap.spec.ts
Labels: Type: Bug / Error, Sponsored by MermaidChart

#6948 DOCS: add newest blog posts
  docs/news/blog.md
  packages/mermaid/src/docs/news/blog.md
Labels: Sponsored by MermaidChart

#6959 chore: remove duplicate changeset file
  .changeset/deep-times-make.md
Labels: Sponsored by MermaidChart

#6958 fix(docs) correct phrasing for architecture icon installation
  docs/syntax/architecture.md
  packages/mermaid/src/docs/syntax/architecture.md
Labels: Type: Bug / Error

#6789 6638:sequence diagram additional messages
  .changeset/loud-results-melt.md
  cypress/integration/rendering/sequencediagram-v2.spec.js
  cypress/integration/rendering/sequencediagram.spec.js
  docs/syntax/sequenceDiagram.md
  packages/mermaid/src/diagrams/sequence/parser/sequenceDiagram.jison
  packages/mermaid/src/diagrams/sequence/sequenceDb.ts
  packages/mermaid/src/diagrams/sequence/sequenceDiagram.spec.js
  packages/mermaid/src/diagrams/sequence/sequenceRenderer.ts
  packages/mermaid/src/diagrams/sequence/svgDraw.js
  packages/mermaid/src/diagrams/sequence/types.ts
  packages/mermaid/src/docs/syntax/sequenceDiagram.md
  packages/mermaid/src/mermaid.spec.ts
Labels: Sponsored by MermaidChart

#6984 fix(er-diagram): handle syntax errors for special characters in node names
  .changeset/sweet-games-build.md
  cypress/integration/rendering/erDiagram.spec.js
  packages/mermaid/src/diagrams/er/parser/erDiagram.jison
  packages/mermaid/src/diagrams/er/parser/erDiagram.spec.js
Labels: Type: Bug / Error, Sponsored by MermaidChart
