Repository mermaid-js/mermaid, pull requests merged in 2025-04, with the labels that each got.

#6445 chore: Downgrade chokidar to 3.6.0 for hot reloading fix
  package.json
  pnpm-lock.yaml
Labels: Type: Other

#6426 Fix formatting of ELK example in ERD + clarify usage
  docs/syntax/entityRelationshipDiagram.md
  packages/mermaid/src/docs/syntax/entityRelationshipDiagram.md
Labels: Area: Documentation, Graph: Entity Relationship

#6407 Fix: greedy regex in common langium
  .changeset/sad-mails-accept.md
  cypress/integration/rendering/architecture.spec.ts
  packages/mermaid/src/diagrams/architecture/architecture.spec.ts
  packages/mermaid/src/diagrams/architecture/architectureDb.ts
  packages/mermaid/src/diagrams/architecture/architectureRenderer.ts
  packages/mermaid/src/diagrams/architecture/architectureTypes.ts
  packages/mermaid/src/diagrams/radar/radar.spec.ts
  packages/mermaid/src/mermaidAPI.spec.ts
  packages/parser/src/language/architecture/arch.langium
  packages/parser/src/language/architecture/architecture.langium
  packages/parser/src/language/common/common.langium
  packages/parser/src/language/gitGraph/gitGraph.langium
  packages/parser/src/language/gitGraph/reference.langium
  packages/parser/src/language/index.ts
  packages/parser/src/language/packet/packet.langium
  packages/parser/src/language/pie/pie.langium
  packages/parser/src/language/radar/radar.langium
  packages/parser/tests/architecture.test.ts
  packages/parser/tests/gitGraph.test.ts
  packages/parser/tests/pie.test.ts
  packages/parser/tests/test-util.ts
Labels: Type: Bug / Error

#6274 fix: Prevent Legend Labels from Overlapping Diagram Elements in Journey Diagrams
  cypress/integration/rendering/journey.spec.js
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/diagrams/user-journey/journeyRenderer.ts
  packages/mermaid/src/schemas/config.schema.yaml
Labels: Type: Bug / Error

#6456 fix(docs): fix edge ID example
  docs/syntax/flowchart.md
  packages/mermaid/src/docs/syntax/flowchart.md
Labels: Type: Bug / Error

#6225 feat: Add support for styling Journey Diagram title (color, font-family, and font-size)
  .changeset/neat-moose-compare.md
  cypress/integration/rendering/journey.spec.js
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/diagrams/user-journey/journeyRenderer.ts
  packages/mermaid/src/schemas/config.schema.yaml
Labels: Type: Enhancement

#6475 feat: Dynamically Render Data Labels Within Bar Charts
  .changeset/soft-readers-tan.md
  cypress/integration/rendering/xyChart.spec.js
  docs/syntax/xyChart.md
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/diagrams/xychart/chartBuilder/interfaces.ts
  packages/mermaid/src/diagrams/xychart/xychartDb.ts
  packages/mermaid/src/diagrams/xychart/xychartRenderer.ts
  packages/mermaid/src/docs/syntax/xyChart.md
  packages/mermaid/src/schemas/config.schema.yaml
Labels: Type: Enhancement

#6491 chore: Switch from `%%{init` to `config:`
  docs/syntax/gitgraph.md
  packages/mermaid/src/docs/syntax/gitgraph.md
Labels: Area: Documentation

#6497 chore: Fix duplicate and missing examples
  docs/config/theming.md
  packages/mermaid/src/docs/config/8.6.0_docs.md
  packages/mermaid/src/docs/config/directives.md
  packages/mermaid/src/docs/config/math.md
  packages/mermaid/src/docs/config/theming.md
  packages/mermaid/src/docs/intro/getting-started.md
  packages/mermaid/src/docs/intro/syntax-reference.md
  packages/mermaid/src/docs/syntax/block.md
  packages/mermaid/src/docs/syntax/classDiagram.md
  packages/mermaid/src/docs/syntax/examples.md
  packages/mermaid/src/docs/syntax/gantt.md
  packages/mermaid/src/docs/syntax/sequenceDiagram.md
Labels: Area: Documentation

#6499 chore: Remove deprecated init config
  docs/config/theming.md
  docs/syntax/flowchart.md
  docs/syntax/pie.md
  docs/syntax/quadrantChart.md
  docs/syntax/radar.md
  docs/syntax/timeline.md
  docs/syntax/xyChart.md
  packages/mermaid/src/docs/config/theming.md
  packages/mermaid/src/docs/syntax/flowchart.md
  packages/mermaid/src/docs/syntax/pie.md
  packages/mermaid/src/docs/syntax/quadrantChart.md
  packages/mermaid/src/docs/syntax/radar.md
  packages/mermaid/src/docs/syntax/timeline.md
  packages/mermaid/src/docs/syntax/xyChart.md
Labels: Area: Documentation

#6343 fix: allow colons in events
  .changeset/ten-lamps-trade.md
  packages/mermaid/src/diagrams/timeline/parser/timeline.jison
  packages/mermaid/src/diagrams/timeline/timeline.spec.js
Labels: Type: Bug / Error

#6340 docs(integrations): add tiki to community list cms/ecm
  docs/ecosystem/integrations-community.md
  packages/mermaid/src/docs/ecosystem/integrations-community.md
Labels: Area: Documentation

#6349 Docs/Fix parameter heading level
  docs/syntax/flowchart.md
  packages/mermaid/src/docs/syntax/flowchart.md
Labels: Area: Documentation

#6523 fix(sequenceDiagram): allow empty message after colon (Fixes #6518)
  .changeset/sixty-deer-tell.md
  packages/mermaid/src/diagrams/sequence/parser/sequenceDiagram.jison
  packages/mermaid/src/diagrams/sequence/sequenceDiagram.spec.js
Labels: Type: Bug / Error

#6479 feat: Add vertical line to gantt plot at specified time
  .changeset/add-vert-tag-bar-chart.md
  cypress/integration/rendering/gantt.spec.js
  docs/syntax/gantt.md
  packages/mermaid/src/diagrams/gantt/ganttDb.js
  packages/mermaid/src/diagrams/gantt/ganttRenderer.js
  packages/mermaid/src/diagrams/gantt/styles.js
  packages/mermaid/src/docs/syntax/gantt.md
  packages/mermaid/src/themes/theme-base.js
  packages/mermaid/src/themes/theme-dark.js
  packages/mermaid/src/themes/theme-default.js
  packages/mermaid/src/themes/theme-forest.js
  packages/mermaid/src/themes/theme-neutral.js
Labels: Type: Enhancement
