Repository mermaid-js/mermaid, pull requests merged in 2025-05, with the labels that each got.

#6541 docs(classDiagram): Clarify annotation syntax and recommend inline st…
  docs/syntax/classDiagram.md
  packages/mermaid/src/docs/syntax/classDiagram.md
Labels: Area: Documentation

#6470 feat(flowchart): add inheritDir option for subgraph direction
  cypress/integration/rendering/flowchart.spec.js
  docs/config/setup/defaultConfig/variables/configKeys.md
  packages/mermaid/src/config.type.ts
  packages/mermaid/src/defaultConfig.ts
  packages/mermaid/src/diagrams/flowchart/flowDb.ts
  packages/mermaid/src/schemas/config.schema.yaml
Labels: Type: Bug / Error

#6423 Feature: Added support for clickable states using the click directive
  .changeset/public-things-stare.md
  packages/mermaid/src/diagrams/state/parser/stateDiagram.jison
  packages/mermaid/src/diagrams/state/stateDb.ts
  packages/mermaid/src/diagrams/state/stateDiagram.spec.js
  packages/mermaid/src/diagrams/state/stateRenderer-v3-unified.ts
Labels: Type: Enhancement

#6581 Upgrade @zenuml/core to v3.31.1.
  .changeset/bitter-colts-remain.md
  demos/zenuml.html
  packages/mermaid-zenuml/package.json
  pnpm-lock.yaml
Labels: Type: Enhancement
