Repository mermaid-js/mermaid, pull requests merged in 2025-08, with the labels that each got.

#6807 Extract tidy-tree layout into separate package
  .build/common.ts
  .github/workflows/validate-lockfile.yml
  packages/mermaid-layout-tidy-tree/README.md
  packages/mermaid-layout-tidy-tree/package.json
  packages/mermaid-layout-tidy-tree/src/index.ts
  packages/mermaid-layout-tidy-tree/src/layout.test.ts
  packages/mermaid-layout-tidy-tree/src/layout.ts
  packages/mermaid-layout-tidy-tree/src/layouts.ts
  packages/mermaid-layout-tidy-tree/src/non-layered-tidy-tree-layout.ts
  packages/mermaid-layout-tidy-tree/src/render.ts
  packages/mermaid-layout-tidy-tree/src/types.ts
  packages/mermaid-layout-tidy-tree/tsconfig.json
  packages/mermaid/src/rendering-util/render.ts
  pnpm-lock.yaml
Labels: Type: Other, Sponsored by MermaidChart

#6820 fix: add classLiteral to the language for class diagram namespace
  .changeset/rare-women-fly.md
  cypress/integration/rendering/classDiagram.spec.js
  packages/mermaid/src/diagrams/class/parser/class.spec.js
  packages/mermaid/src/diagrams/class/parser/classDiagram.jison
Labels: Type: Bug / Error

#6733 Fix: Connection gaps in flowchart shapes
  .changeset/gold-spiders-join.md
  cypress/integration/rendering/flowchart-v2.spec.js
  packages/mermaid/src/rendering-util/rendering-elements/shapes/hexagon.ts
  packages/mermaid/src/rendering-util/rendering-elements/shapes/question.ts
  packages/mermaid/src/rendering-util/rendering-elements/shapes/roundedRect.ts
  packages/mermaid/src/rendering-util/rendering-elements/shapes/stadium.ts
Labels: Sponsored by MermaidChart

#6833 6611: Block diagram shows incorrect arrow direction
  .changeset/strong-dryers-pay.md
  cypress/integration/rendering/block.spec.js
  packages/mermaid/src/diagrams/block/blockDB.ts
Labels: Sponsored by MermaidChart

#6653 #4459: Remove beta suffix
  .changeset/chatty-lemons-stick.md
  cypress/integration/rendering/block.spec.js
  cypress/integration/rendering/sankey.spec.ts
  cypress/integration/rendering/xyChart.spec.js
  demos/block.html
  demos/sankey.html
  demos/xychart.html
  docs/syntax/block.md
  docs/syntax/sankey.md
  docs/syntax/xyChart.md
  packages/mermaid/src/diagrams/block/blockDetector.ts
  packages/mermaid/src/diagrams/block/parser/block.jison
  packages/mermaid/src/diagrams/block/parser/block.spec.ts
  packages/mermaid/src/diagrams/sankey/parser/sankey.jison
  packages/mermaid/src/diagrams/sankey/parser/sankey.spec.ts
  packages/mermaid/src/diagrams/sankey/sankeyDetector.ts
  packages/mermaid/src/diagrams/xychart/parser/xychart.jison
  packages/mermaid/src/diagrams/xychart/parser/xychart.jison.spec.ts
  packages/mermaid/src/diagrams/xychart/xychartDetector.ts
  packages/mermaid/src/docs/syntax/block.md
  packages/mermaid/src/docs/syntax/sankey.md
  packages/mermaid/src/docs/syntax/xyChart.md
  packages/mermaid/src/mermaidAPI.spec.ts
Labels: Sponsored by MermaidChart

#6683 6576: State diagram edge label position
  .changeset/cold-sites-accept.md
  cypress/integration/rendering/stateDiagram-v2.spec.js
  packages/mermaid/src/rendering-util/rendering-elements/edges.js
  packages/mermaid/src/utils.ts
Labels: Graph: State, Sponsored by MermaidChart

#6838 Saurabh/fix-node-border-style-for-hand-drawn-shapes
  .changeset/six-planets-rescue.md
  packages/mermaid/src/rendering-util/rendering-elements/shapes/handDrawnShapeStyles.ts
Labels: Sponsored by MermaidChart

#6839 refactor: remove unnecessary `Element` check since DOMPurify 3.2.2
  packages/mermaid/src/diagrams/common/common.ts
Labels: Type: Other, Sponsored by MermaidChart

#6821 chore: run cspell on lint staged for markdown files
  .lintstagedrc.mjs
Labels: Type: Other

#6861 docs(integrations): update Tiki to Tiki Wiki CMS Groupware community in list cms/ecm to avoid confusion
  docs/ecosystem/integrations-community.md
  packages/mermaid/src/docs/ecosystem/integrations-community.md
Labels: Area: Documentation

#6901 build: stop using `cypress/browsers` for Applitools
  .github/workflows/e2e-applitools.yml
Labels: Sponsored by MermaidChart

#6846 chore: upgrade `unocss@66.4.2` and `@iconify/utils@3.0.1`
  packages/mermaid/package.json
  packages/mermaid/src/docs/package.json
  pnpm-lock.yaml
Labels: Type: Other
